// Mocks generated by Mockito 5.4.6 from annotations
// in chickenjoo_inventory/test/app_test_simple.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i19;

import 'package:chickenjoo_inventory/database/app_database.dart' as _i4;
import 'package:chickenjoo_inventory/database/daos/branch_ingredient_stock_dao.dart'
    as _i12;
import 'package:chickenjoo_inventory/database/daos/branch_item_stock_dao.dart'
    as _i13;
import 'package:chickenjoo_inventory/database/daos/categories_dao.dart' as _i6;
import 'package:chickenjoo_inventory/database/daos/daily_sales_summary_dao.dart'
    as _i16;
import 'package:chickenjoo_inventory/database/daos/ingredients_dao.dart'
    as _i10;
import 'package:chickenjoo_inventory/database/daos/items_dao.dart' as _i9;
import 'package:chickenjoo_inventory/database/daos/organizations_dao.dart'
    as _i5;
import 'package:chickenjoo_inventory/database/daos/recipe_ingredients_dao.dart'
    as _i11;
import 'package:chickenjoo_inventory/database/daos/roles_dao.dart' as _i7;
import 'package:chickenjoo_inventory/database/daos/stock_change_requests_dao.dart'
    as _i15;
import 'package:chickenjoo_inventory/database/daos/stock_replenishment_requests_dao.dart'
    as _i14;
import 'package:chickenjoo_inventory/database/daos/sync_conflicts_dao.dart'
    as _i17;
import 'package:chickenjoo_inventory/database/daos/users_dao.dart' as _i8;
import 'package:chickenjoo_inventory/services/realtime_stock_request_service.dart'
    as _i23;
import 'package:chickenjoo_inventory/services/supabase_auth_service.dart'
    as _i2;
import 'package:chickenjoo_inventory/services/supabase_sync_service_v2.dart'
    as _i22;
import 'package:drift/drift.dart' as _i3;
import 'package:drift/src/runtime/executor/stream_queries.dart' as _i18;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i21;
import 'package:supabase_flutter/supabase_flutter.dart' as _i20;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRolePermissions_0 extends _i1.SmartFake
    implements _i2.RolePermissions {
  _FakeRolePermissions_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthResult_1 extends _i1.SmartFake implements _i2.AuthResult {
  _FakeAuthResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMigrationStrategy_2 extends _i1.SmartFake
    implements _i3.MigrationStrategy {
  _FakeMigrationStrategy_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$AppDatabaseManager_3 extends _i1.SmartFake
    implements _i4.$AppDatabaseManager {
  _Fake$AppDatabaseManager_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$OrganizationsTable_4 extends _i1.SmartFake
    implements _i4.$OrganizationsTable {
  _Fake$OrganizationsTable_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$CategoriesTable_5 extends _i1.SmartFake
    implements _i4.$CategoriesTable {
  _Fake$CategoriesTable_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$RolesTable_6 extends _i1.SmartFake implements _i4.$RolesTable {
  _Fake$RolesTable_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$UsersTable_7 extends _i1.SmartFake implements _i4.$UsersTable {
  _Fake$UsersTable_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$ItemsTable_8 extends _i1.SmartFake implements _i4.$ItemsTable {
  _Fake$ItemsTable_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$IngredientsTable_9 extends _i1.SmartFake
    implements _i4.$IngredientsTable {
  _Fake$IngredientsTable_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$RecipeIngredientsTable_10 extends _i1.SmartFake
    implements _i4.$RecipeIngredientsTable {
  _Fake$RecipeIngredientsTable_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$BranchIngredientStockTable_11 extends _i1.SmartFake
    implements _i4.$BranchIngredientStockTable {
  _Fake$BranchIngredientStockTable_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _Fake$BranchItemStockTable_12 extends _i1.SmartFake
    implements _i4.$BranchItemStockTable {
  _Fake$BranchItemStockTable_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$StockReplenishmentRequestsTable_13 extends _i1.SmartFake
    implements _i4.$StockReplenishmentRequestsTable {
  _Fake$StockReplenishmentRequestsTable_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _Fake$StockChangeRequestsTable_14 extends _i1.SmartFake
    implements _i4.$StockChangeRequestsTable {
  _Fake$StockChangeRequestsTable_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$DailySalesSummaryTable_15 extends _i1.SmartFake
    implements _i4.$DailySalesSummaryTable {
  _Fake$DailySalesSummaryTable_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$SyncConflictsTable_16 extends _i1.SmartFake
    implements _i4.$SyncConflictsTable {
  _Fake$SyncConflictsTable_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrganizationsDao_17 extends _i1.SmartFake
    implements _i5.OrganizationsDao {
  _FakeOrganizationsDao_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCategoriesDao_18 extends _i1.SmartFake implements _i6.CategoriesDao {
  _FakeCategoriesDao_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRolesDao_19 extends _i1.SmartFake implements _i7.RolesDao {
  _FakeRolesDao_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUsersDao_20 extends _i1.SmartFake implements _i8.UsersDao {
  _FakeUsersDao_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeItemsDao_21 extends _i1.SmartFake implements _i9.ItemsDao {
  _FakeItemsDao_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIngredientsDao_22 extends _i1.SmartFake
    implements _i10.IngredientsDao {
  _FakeIngredientsDao_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRecipeIngredientsDao_23 extends _i1.SmartFake
    implements _i11.RecipeIngredientsDao {
  _FakeRecipeIngredientsDao_23(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBranchIngredientStockDao_24 extends _i1.SmartFake
    implements _i12.BranchIngredientStockDao {
  _FakeBranchIngredientStockDao_24(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBranchItemStockDao_25 extends _i1.SmartFake
    implements _i13.BranchItemStockDao {
  _FakeBranchItemStockDao_25(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStockReplenishmentRequestsDao_26 extends _i1.SmartFake
    implements _i14.StockReplenishmentRequestsDao {
  _FakeStockReplenishmentRequestsDao_26(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeStockChangeRequestsDao_27 extends _i1.SmartFake
    implements _i15.StockChangeRequestsDao {
  _FakeStockChangeRequestsDao_27(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDailySalesSummaryDao_28 extends _i1.SmartFake
    implements _i16.DailySalesSummaryDao {
  _FakeDailySalesSummaryDao_28(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSyncConflictsDao_29 extends _i1.SmartFake
    implements _i17.SyncConflictsDao {
  _FakeSyncConflictsDao_29(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamQueryUpdateRules_30 extends _i1.SmartFake
    implements _i3.StreamQueryUpdateRules {
  _FakeStreamQueryUpdateRules_30(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGeneratedDatabase_31 extends _i1.SmartFake
    implements _i3.GeneratedDatabase {
  _FakeGeneratedDatabase_31(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDriftDatabaseOptions_32 extends _i1.SmartFake
    implements _i3.DriftDatabaseOptions {
  _FakeDriftDatabaseOptions_32(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnection_33 extends _i1.SmartFake
    implements _i3.DatabaseConnection {
  _FakeDatabaseConnection_33(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQueryExecutor_34 extends _i1.SmartFake implements _i3.QueryExecutor {
  _FakeQueryExecutor_34(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamQueryStore_35 extends _i1.SmartFake
    implements _i18.StreamQueryStore {
  _FakeStreamQueryStore_35(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnectionUser_36 extends _i1.SmartFake
    implements _i3.DatabaseConnectionUser {
  _FakeDatabaseConnectionUser_36(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_37<T1> extends _i1.SmartFake implements _i19.Future<T1> {
  _FakeFuture_37(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMigrator_38 extends _i1.SmartFake implements _i3.Migrator {
  _FakeMigrator_38(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInsertStatement_39<T1 extends _i3.Table, D1> extends _i1.SmartFake
    implements _i3.InsertStatement<T1, D1> {
  _FakeInsertStatement_39(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateStatement_40<T extends _i3.Table, D> extends _i1.SmartFake
    implements _i3.UpdateStatement<T, D> {
  _FakeUpdateStatement_40(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSimpleSelectStatement_41<T1 extends _i3.HasResultSet, D>
    extends _i1.SmartFake
    implements _i3.SimpleSelectStatement<T1, D> {
  _FakeSimpleSelectStatement_41(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeJoinedSelectStatement_42<FirstT extends _i3.HasResultSet, FirstD>
    extends _i1.SmartFake
    implements _i3.JoinedSelectStatement<FirstT, FirstD> {
  _FakeJoinedSelectStatement_42(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseSelectStatement_43<Row> extends _i1.SmartFake
    implements _i3.BaseSelectStatement<Row> {
  _FakeBaseSelectStatement_43(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeleteStatement_44<T1 extends _i3.Table, D1> extends _i1.SmartFake
    implements _i3.DeleteStatement<T1, D1> {
  _FakeDeleteStatement_44(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSelectable_45<T> extends _i1.SmartFake implements _i3.Selectable<T> {
  _FakeSelectable_45(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGenerationContext_46 extends _i1.SmartFake
    implements _i3.GenerationContext {
  _FakeGenerationContext_46(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAppDatabase_47 extends _i1.SmartFake implements _i4.AppDatabase {
  _FakeAppDatabase_47(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseClient_48 extends _i1.SmartFake
    implements _i20.SupabaseClient {
  _FakeSupabaseClient_48(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrganizationsDaoManager_49 extends _i1.SmartFake
    implements _i5.OrganizationsDaoManager {
  _FakeOrganizationsDaoManager_49(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserData].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserData extends _i1.Mock implements _i2.UserData {
  MockUserData() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get id =>
      (super.noSuchMethod(Invocation.getter(#id), returnValue: 0) as int);

  @override
  String get username =>
      (super.noSuchMethod(
            Invocation.getter(#username),
            returnValue: _i21.dummyValue<String>(
              this,
              Invocation.getter(#username),
            ),
          )
          as String);

  @override
  String get email =>
      (super.noSuchMethod(
            Invocation.getter(#email),
            returnValue: _i21.dummyValue<String>(
              this,
              Invocation.getter(#email),
            ),
          )
          as String);

  @override
  int get organizationId =>
      (super.noSuchMethod(Invocation.getter(#organizationId), returnValue: 0)
          as int);

  @override
  String get organizationType =>
      (super.noSuchMethod(
            Invocation.getter(#organizationType),
            returnValue: _i21.dummyValue<String>(
              this,
              Invocation.getter(#organizationType),
            ),
          )
          as String);

  @override
  String get organizationName =>
      (super.noSuchMethod(
            Invocation.getter(#organizationName),
            returnValue: _i21.dummyValue<String>(
              this,
              Invocation.getter(#organizationName),
            ),
          )
          as String);

  @override
  int get roleId =>
      (super.noSuchMethod(Invocation.getter(#roleId), returnValue: 0) as int);

  @override
  String get roleName =>
      (super.noSuchMethod(
            Invocation.getter(#roleName),
            returnValue: _i21.dummyValue<String>(
              this,
              Invocation.getter(#roleName),
            ),
          )
          as String);

  @override
  _i2.RolePermissions get permissions =>
      (super.noSuchMethod(
            Invocation.getter(#permissions),
            returnValue: _FakeRolePermissions_0(
              this,
              Invocation.getter(#permissions),
            ),
          )
          as _i2.RolePermissions);

  @override
  bool get isCommissary =>
      (super.noSuchMethod(Invocation.getter(#isCommissary), returnValue: false)
          as bool);

  @override
  bool get isFranchisee =>
      (super.noSuchMethod(Invocation.getter(#isFranchisee), returnValue: false)
          as bool);
}

/// A class which mocks [SupabaseAuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseAuthService extends _i1.Mock
    implements _i2.SupabaseAuthService {
  MockSupabaseAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  bool get isCommissary =>
      (super.noSuchMethod(Invocation.getter(#isCommissary), returnValue: false)
          as bool);

  @override
  bool get isFranchisee =>
      (super.noSuchMethod(Invocation.getter(#isFranchisee), returnValue: false)
          as bool);

  @override
  _i19.Stream<_i2.UserData?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i19.Stream<_i2.UserData?>.empty(),
          )
          as _i19.Stream<_i2.UserData?>);

  @override
  _i19.Future<_i2.AuthResult> signUp({
    required String? email,
    required String? password,
    required String? username,
    required String? fullName,
    required int? organizationId,
    required int? roleId,
    String? phone,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {
              #email: email,
              #password: password,
              #username: username,
              #fullName: fullName,
              #organizationId: organizationId,
              #roleId: roleId,
              #phone: phone,
            }),
            returnValue: _i19.Future<_i2.AuthResult>.value(
              _FakeAuthResult_1(
                this,
                Invocation.method(#signUp, [], {
                  #email: email,
                  #password: password,
                  #username: username,
                  #fullName: fullName,
                  #organizationId: organizationId,
                  #roleId: roleId,
                  #phone: phone,
                }),
              ),
            ),
          )
          as _i19.Future<_i2.AuthResult>);

  @override
  _i19.Future<_i2.AuthResult> signIn({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i19.Future<_i2.AuthResult>.value(
              _FakeAuthResult_1(
                this,
                Invocation.method(#signIn, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i19.Future<_i2.AuthResult>);

  @override
  _i19.Future<_i2.AuthResult> createEmployee({
    required String? email,
    required String? username,
    required String? password,
    required int? organizationId,
    required int? roleId,
    String? fullName,
    String? phone,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createEmployee, [], {
              #email: email,
              #username: username,
              #password: password,
              #organizationId: organizationId,
              #roleId: roleId,
              #fullName: fullName,
              #phone: phone,
            }),
            returnValue: _i19.Future<_i2.AuthResult>.value(
              _FakeAuthResult_1(
                this,
                Invocation.method(#createEmployee, [], {
                  #email: email,
                  #username: username,
                  #password: password,
                  #organizationId: organizationId,
                  #roleId: roleId,
                  #fullName: fullName,
                  #phone: phone,
                }),
              ),
            ),
          )
          as _i19.Future<_i2.AuthResult>);

  @override
  _i19.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i19.Future<void>.value(),
            returnValueForMissingStub: _i19.Future<void>.value(),
          )
          as _i19.Future<void>);

  @override
  _i19.Future<_i2.AuthResult> resetPassword(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [email]),
            returnValue: _i19.Future<_i2.AuthResult>.value(
              _FakeAuthResult_1(
                this,
                Invocation.method(#resetPassword, [email]),
              ),
            ),
          )
          as _i19.Future<_i2.AuthResult>);

  @override
  _i19.Future<_i2.AuthResult> updatePassword(String? newPassword) =>
      (super.noSuchMethod(
            Invocation.method(#updatePassword, [newPassword]),
            returnValue: _i19.Future<_i2.AuthResult>.value(
              _FakeAuthResult_1(
                this,
                Invocation.method(#updatePassword, [newPassword]),
              ),
            ),
          )
          as _i19.Future<_i2.AuthResult>);

  @override
  _i19.Future<bool> isSessionValid() =>
      (super.noSuchMethod(
            Invocation.method(#isSessionValid, []),
            returnValue: _i19.Future<bool>.value(false),
          )
          as _i19.Future<bool>);

  @override
  _i19.Future<_i2.AuthResult> restoreSession() =>
      (super.noSuchMethod(
            Invocation.method(#restoreSession, []),
            returnValue: _i19.Future<_i2.AuthResult>.value(
              _FakeAuthResult_1(this, Invocation.method(#restoreSession, [])),
            ),
          )
          as _i19.Future<_i2.AuthResult>);

  @override
  _i19.Future<void> refreshSession() =>
      (super.noSuchMethod(
            Invocation.method(#refreshSession, []),
            returnValue: _i19.Future<void>.value(),
            returnValueForMissingStub: _i19.Future<void>.value(),
          )
          as _i19.Future<void>);

  @override
  _i19.Future<({List<Map<String, dynamic>> branches, bool isOffline})>
  fetchAvailableBranches() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAvailableBranches, []),
            returnValue:
                _i19.Future<
                  ({List<Map<String, dynamic>> branches, bool isOffline})
                >.value((branches: <Map<String, dynamic>>[], isOffline: false)),
          )
          as _i19.Future<
            ({List<Map<String, dynamic>> branches, bool isOffline})
          >);

  @override
  _i19.Future<_i2.AuthResult> signInToBranch({
    required String? email,
    required String? password,
    required String? branchCloudId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInToBranch, [], {
              #email: email,
              #password: password,
              #branchCloudId: branchCloudId,
            }),
            returnValue: _i19.Future<_i2.AuthResult>.value(
              _FakeAuthResult_1(
                this,
                Invocation.method(#signInToBranch, [], {
                  #email: email,
                  #password: password,
                  #branchCloudId: branchCloudId,
                }),
              ),
            ),
          )
          as _i19.Future<_i2.AuthResult>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AppDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppDatabase extends _i1.Mock implements _i4.AppDatabase {
  MockAppDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get schemaVersion =>
      (super.noSuchMethod(Invocation.getter(#schemaVersion), returnValue: 0)
          as int);

  @override
  _i3.MigrationStrategy get migration =>
      (super.noSuchMethod(
            Invocation.getter(#migration),
            returnValue: _FakeMigrationStrategy_2(
              this,
              Invocation.getter(#migration),
            ),
          )
          as _i3.MigrationStrategy);

  @override
  _i4.$AppDatabaseManager get managers =>
      (super.noSuchMethod(
            Invocation.getter(#managers),
            returnValue: _Fake$AppDatabaseManager_3(
              this,
              Invocation.getter(#managers),
            ),
          )
          as _i4.$AppDatabaseManager);

  @override
  _i4.$OrganizationsTable get organizations =>
      (super.noSuchMethod(
            Invocation.getter(#organizations),
            returnValue: _Fake$OrganizationsTable_4(
              this,
              Invocation.getter(#organizations),
            ),
          )
          as _i4.$OrganizationsTable);

  @override
  _i4.$CategoriesTable get categories =>
      (super.noSuchMethod(
            Invocation.getter(#categories),
            returnValue: _Fake$CategoriesTable_5(
              this,
              Invocation.getter(#categories),
            ),
          )
          as _i4.$CategoriesTable);

  @override
  _i4.$RolesTable get roles =>
      (super.noSuchMethod(
            Invocation.getter(#roles),
            returnValue: _Fake$RolesTable_6(this, Invocation.getter(#roles)),
          )
          as _i4.$RolesTable);

  @override
  _i4.$UsersTable get users =>
      (super.noSuchMethod(
            Invocation.getter(#users),
            returnValue: _Fake$UsersTable_7(this, Invocation.getter(#users)),
          )
          as _i4.$UsersTable);

  @override
  _i4.$ItemsTable get items =>
      (super.noSuchMethod(
            Invocation.getter(#items),
            returnValue: _Fake$ItemsTable_8(this, Invocation.getter(#items)),
          )
          as _i4.$ItemsTable);

  @override
  _i4.$IngredientsTable get ingredients =>
      (super.noSuchMethod(
            Invocation.getter(#ingredients),
            returnValue: _Fake$IngredientsTable_9(
              this,
              Invocation.getter(#ingredients),
            ),
          )
          as _i4.$IngredientsTable);

  @override
  _i4.$RecipeIngredientsTable get recipeIngredients =>
      (super.noSuchMethod(
            Invocation.getter(#recipeIngredients),
            returnValue: _Fake$RecipeIngredientsTable_10(
              this,
              Invocation.getter(#recipeIngredients),
            ),
          )
          as _i4.$RecipeIngredientsTable);

  @override
  _i4.$BranchIngredientStockTable get branchIngredientStock =>
      (super.noSuchMethod(
            Invocation.getter(#branchIngredientStock),
            returnValue: _Fake$BranchIngredientStockTable_11(
              this,
              Invocation.getter(#branchIngredientStock),
            ),
          )
          as _i4.$BranchIngredientStockTable);

  @override
  _i4.$BranchItemStockTable get branchItemStock =>
      (super.noSuchMethod(
            Invocation.getter(#branchItemStock),
            returnValue: _Fake$BranchItemStockTable_12(
              this,
              Invocation.getter(#branchItemStock),
            ),
          )
          as _i4.$BranchItemStockTable);

  @override
  _i4.$StockReplenishmentRequestsTable get stockReplenishmentRequests =>
      (super.noSuchMethod(
            Invocation.getter(#stockReplenishmentRequests),
            returnValue: _Fake$StockReplenishmentRequestsTable_13(
              this,
              Invocation.getter(#stockReplenishmentRequests),
            ),
          )
          as _i4.$StockReplenishmentRequestsTable);

  @override
  _i4.$StockChangeRequestsTable get stockChangeRequests =>
      (super.noSuchMethod(
            Invocation.getter(#stockChangeRequests),
            returnValue: _Fake$StockChangeRequestsTable_14(
              this,
              Invocation.getter(#stockChangeRequests),
            ),
          )
          as _i4.$StockChangeRequestsTable);

  @override
  _i4.$DailySalesSummaryTable get dailySalesSummary =>
      (super.noSuchMethod(
            Invocation.getter(#dailySalesSummary),
            returnValue: _Fake$DailySalesSummaryTable_15(
              this,
              Invocation.getter(#dailySalesSummary),
            ),
          )
          as _i4.$DailySalesSummaryTable);

  @override
  _i4.$SyncConflictsTable get syncConflicts =>
      (super.noSuchMethod(
            Invocation.getter(#syncConflicts),
            returnValue: _Fake$SyncConflictsTable_16(
              this,
              Invocation.getter(#syncConflicts),
            ),
          )
          as _i4.$SyncConflictsTable);

  @override
  _i5.OrganizationsDao get organizationsDao =>
      (super.noSuchMethod(
            Invocation.getter(#organizationsDao),
            returnValue: _FakeOrganizationsDao_17(
              this,
              Invocation.getter(#organizationsDao),
            ),
          )
          as _i5.OrganizationsDao);

  @override
  _i6.CategoriesDao get categoriesDao =>
      (super.noSuchMethod(
            Invocation.getter(#categoriesDao),
            returnValue: _FakeCategoriesDao_18(
              this,
              Invocation.getter(#categoriesDao),
            ),
          )
          as _i6.CategoriesDao);

  @override
  _i7.RolesDao get rolesDao =>
      (super.noSuchMethod(
            Invocation.getter(#rolesDao),
            returnValue: _FakeRolesDao_19(this, Invocation.getter(#rolesDao)),
          )
          as _i7.RolesDao);

  @override
  _i8.UsersDao get usersDao =>
      (super.noSuchMethod(
            Invocation.getter(#usersDao),
            returnValue: _FakeUsersDao_20(this, Invocation.getter(#usersDao)),
          )
          as _i8.UsersDao);

  @override
  _i9.ItemsDao get itemsDao =>
      (super.noSuchMethod(
            Invocation.getter(#itemsDao),
            returnValue: _FakeItemsDao_21(this, Invocation.getter(#itemsDao)),
          )
          as _i9.ItemsDao);

  @override
  _i10.IngredientsDao get ingredientsDao =>
      (super.noSuchMethod(
            Invocation.getter(#ingredientsDao),
            returnValue: _FakeIngredientsDao_22(
              this,
              Invocation.getter(#ingredientsDao),
            ),
          )
          as _i10.IngredientsDao);

  @override
  _i11.RecipeIngredientsDao get recipeIngredientsDao =>
      (super.noSuchMethod(
            Invocation.getter(#recipeIngredientsDao),
            returnValue: _FakeRecipeIngredientsDao_23(
              this,
              Invocation.getter(#recipeIngredientsDao),
            ),
          )
          as _i11.RecipeIngredientsDao);

  @override
  _i12.BranchIngredientStockDao get branchIngredientStockDao =>
      (super.noSuchMethod(
            Invocation.getter(#branchIngredientStockDao),
            returnValue: _FakeBranchIngredientStockDao_24(
              this,
              Invocation.getter(#branchIngredientStockDao),
            ),
          )
          as _i12.BranchIngredientStockDao);

  @override
  _i13.BranchItemStockDao get branchItemStockDao =>
      (super.noSuchMethod(
            Invocation.getter(#branchItemStockDao),
            returnValue: _FakeBranchItemStockDao_25(
              this,
              Invocation.getter(#branchItemStockDao),
            ),
          )
          as _i13.BranchItemStockDao);

  @override
  _i14.StockReplenishmentRequestsDao get stockReplenishmentRequestsDao =>
      (super.noSuchMethod(
            Invocation.getter(#stockReplenishmentRequestsDao),
            returnValue: _FakeStockReplenishmentRequestsDao_26(
              this,
              Invocation.getter(#stockReplenishmentRequestsDao),
            ),
          )
          as _i14.StockReplenishmentRequestsDao);

  @override
  _i15.StockChangeRequestsDao get stockChangeRequestsDao =>
      (super.noSuchMethod(
            Invocation.getter(#stockChangeRequestsDao),
            returnValue: _FakeStockChangeRequestsDao_27(
              this,
              Invocation.getter(#stockChangeRequestsDao),
            ),
          )
          as _i15.StockChangeRequestsDao);

  @override
  _i16.DailySalesSummaryDao get dailySalesSummaryDao =>
      (super.noSuchMethod(
            Invocation.getter(#dailySalesSummaryDao),
            returnValue: _FakeDailySalesSummaryDao_28(
              this,
              Invocation.getter(#dailySalesSummaryDao),
            ),
          )
          as _i16.DailySalesSummaryDao);

  @override
  _i17.SyncConflictsDao get syncConflictsDao =>
      (super.noSuchMethod(
            Invocation.getter(#syncConflictsDao),
            returnValue: _FakeSyncConflictsDao_29(
              this,
              Invocation.getter(#syncConflictsDao),
            ),
          )
          as _i17.SyncConflictsDao);

  @override
  Iterable<_i3.TableInfo<_i3.Table, Object?>> get allTables =>
      (super.noSuchMethod(
            Invocation.getter(#allTables),
            returnValue: <_i3.TableInfo<_i3.Table, Object?>>[],
          )
          as Iterable<_i3.TableInfo<_i3.Table, Object?>>);

  @override
  List<_i3.DatabaseSchemaEntity> get allSchemaEntities =>
      (super.noSuchMethod(
            Invocation.getter(#allSchemaEntities),
            returnValue: <_i3.DatabaseSchemaEntity>[],
          )
          as List<_i3.DatabaseSchemaEntity>);

  @override
  _i3.StreamQueryUpdateRules get streamUpdateRules =>
      (super.noSuchMethod(
            Invocation.getter(#streamUpdateRules),
            returnValue: _FakeStreamQueryUpdateRules_30(
              this,
              Invocation.getter(#streamUpdateRules),
            ),
          )
          as _i3.StreamQueryUpdateRules);

  @override
  _i3.GeneratedDatabase get attachedDatabase =>
      (super.noSuchMethod(
            Invocation.getter(#attachedDatabase),
            returnValue: _FakeGeneratedDatabase_31(
              this,
              Invocation.getter(#attachedDatabase),
            ),
          )
          as _i3.GeneratedDatabase);

  @override
  _i3.DriftDatabaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeDriftDatabaseOptions_32(
              this,
              Invocation.getter(#options),
            ),
          )
          as _i3.DriftDatabaseOptions);

  @override
  _i3.DatabaseConnection get connection =>
      (super.noSuchMethod(
            Invocation.getter(#connection),
            returnValue: _FakeDatabaseConnection_33(
              this,
              Invocation.getter(#connection),
            ),
          )
          as _i3.DatabaseConnection);

  @override
  _i3.SqlTypes get typeMapping =>
      (super.noSuchMethod(
            Invocation.getter(#typeMapping),
            returnValue: _i21.dummyValue<_i3.SqlTypes>(
              this,
              Invocation.getter(#typeMapping),
            ),
          )
          as _i3.SqlTypes);

  @override
  _i3.QueryExecutor get executor =>
      (super.noSuchMethod(
            Invocation.getter(#executor),
            returnValue: _FakeQueryExecutor_34(
              this,
              Invocation.getter(#executor),
            ),
          )
          as _i3.QueryExecutor);

  @override
  _i18.StreamQueryStore get streamQueries =>
      (super.noSuchMethod(
            Invocation.getter(#streamQueries),
            returnValue: _FakeStreamQueryStore_35(
              this,
              Invocation.getter(#streamQueries),
            ),
          )
          as _i18.StreamQueryStore);

  @override
  _i3.DatabaseConnectionUser get resolvedEngine =>
      (super.noSuchMethod(
            Invocation.getter(#resolvedEngine),
            returnValue: _FakeDatabaseConnectionUser_36(
              this,
              Invocation.getter(#resolvedEngine),
            ),
          )
          as _i3.DatabaseConnectionUser);

  @override
  _i19.Future<T> executeInTransaction<T>(_i19.Future<T> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#executeInTransaction, [action]),
            returnValue:
                _i21.ifNotNull(
                  _i21.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#executeInTransaction, [action]),
                  ),
                  (T v) => _i19.Future<T>.value(v),
                ) ??
                _FakeFuture_37<T>(
                  this,
                  Invocation.method(#executeInTransaction, [action]),
                ),
          )
          as _i19.Future<T>);

  @override
  _i3.Migrator createMigrator() =>
      (super.noSuchMethod(
            Invocation.method(#createMigrator, []),
            returnValue: _FakeMigrator_38(
              this,
              Invocation.method(#createMigrator, []),
            ),
          )
          as _i3.Migrator);

  @override
  _i19.Future<void> beforeOpen(
    _i3.QueryExecutor? executor,
    _i3.OpeningDetails? details,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#beforeOpen, [executor, details]),
            returnValue: _i19.Future<void>.value(),
            returnValueForMissingStub: _i19.Future<void>.value(),
          )
          as _i19.Future<void>);

  @override
  _i19.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i19.Future<void>.value(),
            returnValueForMissingStub: _i19.Future<void>.value(),
          )
          as _i19.Future<void>);

  @override
  _i19.Future<Ret> computeWithDatabase<Ret, DB extends _i3.GeneratedDatabase>({
    required _i19.FutureOr<Ret> Function(DB)? computation,
    required DB Function(_i3.DatabaseConnection)? connect,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#computeWithDatabase, [], {
              #computation: computation,
              #connect: connect,
            }),
            returnValue:
                _i21.ifNotNull(
                  _i21.dummyValueOrNull<Ret>(
                    this,
                    Invocation.method(#computeWithDatabase, [], {
                      #computation: computation,
                      #connect: connect,
                    }),
                  ),
                  (Ret v) => _i19.Future<Ret>.value(v),
                ) ??
                _FakeFuture_37<Ret>(
                  this,
                  Invocation.method(#computeWithDatabase, [], {
                    #computation: computation,
                    #connect: connect,
                  }),
                ),
          )
          as _i19.Future<Ret>);

  @override
  _i19.Stream<T> createStream<T extends Object>(
    _i18.QueryStreamFetcher<T>? stmt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createStream, [stmt]),
            returnValue: _i19.Stream<T>.empty(),
          )
          as _i19.Stream<T>);

  @override
  T alias<T, D>(_i3.ResultSetImplementation<T, D>? table, String? alias) =>
      (super.noSuchMethod(
            Invocation.method(#alias, [table, alias]),
            returnValue: _i21.dummyValue<T>(
              this,
              Invocation.method(#alias, [table, alias]),
            ),
          )
          as T);

  @override
  void markTablesUpdated(Iterable<_i3.TableInfo<_i3.Table, dynamic>>? tables) =>
      super.noSuchMethod(
        Invocation.method(#markTablesUpdated, [tables]),
        returnValueForMissingStub: null,
      );

  @override
  void notifyUpdates(Set<_i3.TableUpdate>? updates) => super.noSuchMethod(
    Invocation.method(#notifyUpdates, [updates]),
    returnValueForMissingStub: null,
  );

  @override
  _i19.Stream<Set<_i3.TableUpdate>> tableUpdates([
    _i3.TableUpdateQuery? query = const _i3.TableUpdateQuery.any(),
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#tableUpdates, [query]),
            returnValue: _i19.Stream<Set<_i3.TableUpdate>>.empty(),
          )
          as _i19.Stream<Set<_i3.TableUpdate>>);

  @override
  _i19.Future<T> doWhenOpened<T>(
    _i19.FutureOr<T> Function(_i3.QueryExecutor)? fn,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#doWhenOpened, [fn]),
            returnValue:
                _i21.ifNotNull(
                  _i21.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#doWhenOpened, [fn]),
                  ),
                  (T v) => _i19.Future<T>.value(v),
                ) ??
                _FakeFuture_37<T>(this, Invocation.method(#doWhenOpened, [fn])),
          )
          as _i19.Future<T>);

  @override
  _i3.InsertStatement<T, D> into<T extends _i3.Table, D>(
    _i3.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#into, [table]),
            returnValue: _FakeInsertStatement_39<T, D>(
              this,
              Invocation.method(#into, [table]),
            ),
          )
          as _i3.InsertStatement<T, D>);

  @override
  _i3.UpdateStatement<Tbl, R> update<Tbl extends _i3.Table, R>(
    _i3.TableInfo<Tbl, R>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [table]),
            returnValue: _FakeUpdateStatement_40<Tbl, R>(
              this,
              Invocation.method(#update, [table]),
            ),
          )
          as _i3.UpdateStatement<Tbl, R>);

  @override
  _i3.SimpleSelectStatement<T, R> select<T extends _i3.HasResultSet, R>(
    _i3.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#select, [table], {#distinct: distinct}),
            returnValue: _FakeSimpleSelectStatement_41<T, R>(
              this,
              Invocation.method(#select, [table], {#distinct: distinct}),
            ),
          )
          as _i3.SimpleSelectStatement<T, R>);

  @override
  _i3.JoinedSelectStatement<T, R> selectOnly<T extends _i3.HasResultSet, R>(
    _i3.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            returnValue: _FakeJoinedSelectStatement_42<T, R>(
              this,
              Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            ),
          )
          as _i3.JoinedSelectStatement<T, R>);

  @override
  _i3.BaseSelectStatement<_i3.TypedResult> selectExpressions(
    Iterable<_i3.Expression<Object>>? columns,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#selectExpressions, [columns]),
            returnValue: _FakeBaseSelectStatement_43<_i3.TypedResult>(
              this,
              Invocation.method(#selectExpressions, [columns]),
            ),
          )
          as _i3.BaseSelectStatement<_i3.TypedResult>);

  @override
  _i3.DeleteStatement<T, D> delete<T extends _i3.Table, D>(
    _i3.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [table]),
            returnValue: _FakeDeleteStatement_44<T, D>(
              this,
              Invocation.method(#delete, [table]),
            ),
          )
          as _i3.DeleteStatement<T, D>);

  @override
  _i19.Future<int> customUpdate(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i3.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customUpdate,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i19.Future<int>.value(0),
          )
          as _i19.Future<int>);

  @override
  _i19.Future<int> customInsert(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customInsert,
              [query],
              {#variables: variables, #updates: updates},
            ),
            returnValue: _i19.Future<int>.value(0),
          )
          as _i19.Future<int>);

  @override
  _i19.Future<List<_i3.QueryRow>> customWriteReturning(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i3.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customWriteReturning,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i19.Future<List<_i3.QueryRow>>.value(
              <_i3.QueryRow>[],
            ),
          )
          as _i19.Future<List<_i3.QueryRow>>);

  @override
  _i3.Selectable<_i3.QueryRow> customSelect(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelect,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_45<_i3.QueryRow>(
              this,
              Invocation.method(
                #customSelect,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i3.Selectable<_i3.QueryRow>);

  @override
  _i3.Selectable<_i3.QueryRow> customSelectQuery(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelectQuery,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_45<_i3.QueryRow>(
              this,
              Invocation.method(
                #customSelectQuery,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i3.Selectable<_i3.QueryRow>);

  @override
  _i19.Future<void> customStatement(String? statement, [List<dynamic>? args]) =>
      (super.noSuchMethod(
            Invocation.method(#customStatement, [statement, args]),
            returnValue: _i19.Future<void>.value(),
            returnValueForMissingStub: _i19.Future<void>.value(),
          )
          as _i19.Future<void>);

  @override
  _i19.Future<T> transaction<T>(
    _i19.Future<T> Function()? action, {
    bool? requireNew = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #transaction,
              [action],
              {#requireNew: requireNew},
            ),
            returnValue:
                _i21.ifNotNull(
                  _i21.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #transaction,
                      [action],
                      {#requireNew: requireNew},
                    ),
                  ),
                  (T v) => _i19.Future<T>.value(v),
                ) ??
                _FakeFuture_37<T>(
                  this,
                  Invocation.method(
                    #transaction,
                    [action],
                    {#requireNew: requireNew},
                  ),
                ),
          )
          as _i19.Future<T>);

  @override
  _i19.Future<T> exclusively<T>(_i19.Future<T> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#exclusively, [action]),
            returnValue:
                _i21.ifNotNull(
                  _i21.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#exclusively, [action]),
                  ),
                  (T v) => _i19.Future<T>.value(v),
                ) ??
                _FakeFuture_37<T>(
                  this,
                  Invocation.method(#exclusively, [action]),
                ),
          )
          as _i19.Future<T>);

  @override
  _i19.Future<void> batch(
    _i19.FutureOr<void> Function(_i3.Batch)? runInBatch,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#batch, [runInBatch]),
            returnValue: _i19.Future<void>.value(),
            returnValueForMissingStub: _i19.Future<void>.value(),
          )
          as _i19.Future<void>);

  @override
  _i19.Future<T> runWithInterceptor<T>(
    _i19.Future<T> Function()? action, {
    required _i3.QueryInterceptor? interceptor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #runWithInterceptor,
              [action],
              {#interceptor: interceptor},
            ),
            returnValue:
                _i21.ifNotNull(
                  _i21.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #runWithInterceptor,
                      [action],
                      {#interceptor: interceptor},
                    ),
                  ),
                  (T v) => _i19.Future<T>.value(v),
                ) ??
                _FakeFuture_37<T>(
                  this,
                  Invocation.method(
                    #runWithInterceptor,
                    [action],
                    {#interceptor: interceptor},
                  ),
                ),
          )
          as _i19.Future<T>);

  @override
  _i3.GenerationContext $write(
    _i3.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$write,
              [component],
              {#hasMultipleTables: hasMultipleTables, #startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_46(
              this,
              Invocation.method(
                #$write,
                [component],
                {
                  #hasMultipleTables: hasMultipleTables,
                  #startIndex: startIndex,
                },
              ),
            ),
          )
          as _i3.GenerationContext);

  @override
  _i3.GenerationContext $writeInsertable(
    _i3.TableInfo<_i3.Table, dynamic>? table,
    _i3.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$writeInsertable,
              [table, insertable],
              {#startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_46(
              this,
              Invocation.method(
                #$writeInsertable,
                [table, insertable],
                {#startIndex: startIndex},
              ),
            ),
          )
          as _i3.GenerationContext);

  @override
  String $expandVar(int? start, int? amount) =>
      (super.noSuchMethod(
            Invocation.method(#$expandVar, [start, amount]),
            returnValue: _i21.dummyValue<String>(
              this,
              Invocation.method(#$expandVar, [start, amount]),
            ),
          )
          as String);
}

/// A class which mocks [SupabaseSyncServiceV2].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseSyncServiceV2 extends _i1.Mock
    implements _i22.SupabaseSyncServiceV2 {
  MockSupabaseSyncServiceV2() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.AppDatabase get db =>
      (super.noSuchMethod(
            Invocation.getter(#db),
            returnValue: _FakeAppDatabase_47(this, Invocation.getter(#db)),
          )
          as _i4.AppDatabase);

  @override
  _i20.SupabaseClient get supabase =>
      (super.noSuchMethod(
            Invocation.getter(#supabase),
            returnValue: _FakeSupabaseClient_48(
              this,
              Invocation.getter(#supabase),
            ),
          )
          as _i20.SupabaseClient);

  @override
  bool get canSync =>
      (super.noSuchMethod(Invocation.getter(#canSync), returnValue: false)
          as bool);

  @override
  set onConnectivityChanged(dynamic Function(bool)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onConnectivityChanged, value),
        returnValueForMissingStub: null,
      );

  @override
  set onSyncStatusChanged(dynamic Function(String)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onSyncStatusChanged, value),
        returnValueForMissingStub: null,
      );

  @override
  set onSyncError(dynamic Function(String)? value) => super.noSuchMethod(
    Invocation.setter(#onSyncError, value),
    returnValueForMissingStub: null,
  );

  @override
  set onSyncProgress(dynamic Function(double, String)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onSyncProgress, value),
        returnValueForMissingStub: null,
      );

  @override
  set onSyncComplete(dynamic Function()? value) => super.noSuchMethod(
    Invocation.setter(#onSyncComplete, value),
    returnValueForMissingStub: null,
  );

  @override
  set onConflictDetected(dynamic Function(String, String)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onConflictDetected, value),
        returnValueForMissingStub: null,
      );

  @override
  _i19.Future<void> initialize({
    int? organizationId,
    String? organizationCloudId,
    String? organizationType,
    int? parentCommissaryId,
    String? parentCommissaryCloudId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [], {
              #organizationId: organizationId,
              #organizationCloudId: organizationCloudId,
              #organizationType: organizationType,
              #parentCommissaryId: parentCommissaryId,
              #parentCommissaryCloudId: parentCommissaryCloudId,
            }),
            returnValue: _i19.Future<void>.value(),
            returnValueForMissingStub: _i19.Future<void>.value(),
          )
          as _i19.Future<void>);

  @override
  void startPeriodicSync() => super.noSuchMethod(
    Invocation.method(#startPeriodicSync, []),
    returnValueForMissingStub: null,
  );

  @override
  void stopPeriodicSync() => super.noSuchMethod(
    Invocation.method(#stopPeriodicSync, []),
    returnValueForMissingStub: null,
  );

  @override
  _i19.Future<void> syncAll() =>
      (super.noSuchMethod(
            Invocation.method(#syncAll, []),
            returnValue: _i19.Future<void>.value(),
            returnValueForMissingStub: _i19.Future<void>.value(),
          )
          as _i19.Future<void>);

  @override
  _i19.Future<void> syncImmediate() =>
      (super.noSuchMethod(
            Invocation.method(#syncImmediate, []),
            returnValue: _i19.Future<void>.value(),
            returnValueForMissingStub: _i19.Future<void>.value(),
          )
          as _i19.Future<void>);

  @override
  _i19.Future<void> syncItemsOnly() =>
      (super.noSuchMethod(
            Invocation.method(#syncItemsOnly, []),
            returnValue: _i19.Future<void>.value(),
            returnValueForMissingStub: _i19.Future<void>.value(),
          )
          as _i19.Future<void>);

  @override
  _i19.Future<void> syncOrganizations() =>
      (super.noSuchMethod(
            Invocation.method(#syncOrganizations, []),
            returnValue: _i19.Future<void>.value(),
            returnValueForMissingStub: _i19.Future<void>.value(),
          )
          as _i19.Future<void>);

  @override
  _i19.Future<void> syncRoles() =>
      (super.noSuchMethod(
            Invocation.method(#syncRoles, []),
            returnValue: _i19.Future<void>.value(),
            returnValueForMissingStub: _i19.Future<void>.value(),
          )
          as _i19.Future<void>);

  @override
  _i19.Future<void> syncUsers() =>
      (super.noSuchMethod(
            Invocation.method(#syncUsers, []),
            returnValue: _i19.Future<void>.value(),
            returnValueForMissingStub: _i19.Future<void>.value(),
          )
          as _i19.Future<void>);

  @override
  _i19.Future<void> syncItems() =>
      (super.noSuchMethod(
            Invocation.method(#syncItems, []),
            returnValue: _i19.Future<void>.value(),
            returnValueForMissingStub: _i19.Future<void>.value(),
          )
          as _i19.Future<void>);

  @override
  _i19.Future<void> syncIngredients() =>
      (super.noSuchMethod(
            Invocation.method(#syncIngredients, []),
            returnValue: _i19.Future<void>.value(),
            returnValueForMissingStub: _i19.Future<void>.value(),
          )
          as _i19.Future<void>);

  @override
  _i19.Future<void> syncRecipeIngredients() =>
      (super.noSuchMethod(
            Invocation.method(#syncRecipeIngredients, []),
            returnValue: _i19.Future<void>.value(),
            returnValueForMissingStub: _i19.Future<void>.value(),
          )
          as _i19.Future<void>);

  @override
  _i19.Future<void> syncStockReplenishmentRequests() =>
      (super.noSuchMethod(
            Invocation.method(#syncStockReplenishmentRequests, []),
            returnValue: _i19.Future<void>.value(),
            returnValueForMissingStub: _i19.Future<void>.value(),
          )
          as _i19.Future<void>);

  @override
  _i19.Future<void> syncStockChangeRequests() =>
      (super.noSuchMethod(
            Invocation.method(#syncStockChangeRequests, []),
            returnValue: _i19.Future<void>.value(),
            returnValueForMissingStub: _i19.Future<void>.value(),
          )
          as _i19.Future<void>);

  @override
  _i19.Future<void> syncBranchItemStock() =>
      (super.noSuchMethod(
            Invocation.method(#syncBranchItemStock, []),
            returnValue: _i19.Future<void>.value(),
            returnValueForMissingStub: _i19.Future<void>.value(),
          )
          as _i19.Future<void>);

  @override
  _i19.Future<void> syncBranchIngredientStock() =>
      (super.noSuchMethod(
            Invocation.method(#syncBranchIngredientStock, []),
            returnValue: _i19.Future<void>.value(),
            returnValueForMissingStub: _i19.Future<void>.value(),
          )
          as _i19.Future<void>);

  @override
  _i19.Future<void> syncDailySalesSummary() =>
      (super.noSuchMethod(
            Invocation.method(#syncDailySalesSummary, []),
            returnValue: _i19.Future<void>.value(),
            returnValueForMissingStub: _i19.Future<void>.value(),
          )
          as _i19.Future<void>);

  @override
  _i19.Future<Map<String, dynamic>> getSyncStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getSyncStatus, []),
            returnValue: _i19.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i19.Future<Map<String, dynamic>>);

  @override
  void setOrganizationContext({
    required int? organizationId,
    required String? organizationType,
    int? parentCommissaryId,
  }) => super.noSuchMethod(
    Invocation.method(#setOrganizationContext, [], {
      #organizationId: organizationId,
      #organizationType: organizationType,
      #parentCommissaryId: parentCommissaryId,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [OrganizationsDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrganizationsDao extends _i1.Mock implements _i5.OrganizationsDao {
  MockOrganizationsDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.AppDatabase get attachedDatabase =>
      (super.noSuchMethod(
            Invocation.getter(#attachedDatabase),
            returnValue: _FakeAppDatabase_47(
              this,
              Invocation.getter(#attachedDatabase),
            ),
          )
          as _i4.AppDatabase);

  @override
  _i3.DatabaseConnection get connection =>
      (super.noSuchMethod(
            Invocation.getter(#connection),
            returnValue: _FakeDatabaseConnection_33(
              this,
              Invocation.getter(#connection),
            ),
          )
          as _i3.DatabaseConnection);

  @override
  _i3.DriftDatabaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeDriftDatabaseOptions_32(
              this,
              Invocation.getter(#options),
            ),
          )
          as _i3.DriftDatabaseOptions);

  @override
  _i3.SqlTypes get typeMapping =>
      (super.noSuchMethod(
            Invocation.getter(#typeMapping),
            returnValue: _i21.dummyValue<_i3.SqlTypes>(
              this,
              Invocation.getter(#typeMapping),
            ),
          )
          as _i3.SqlTypes);

  @override
  _i3.QueryExecutor get executor =>
      (super.noSuchMethod(
            Invocation.getter(#executor),
            returnValue: _FakeQueryExecutor_34(
              this,
              Invocation.getter(#executor),
            ),
          )
          as _i3.QueryExecutor);

  @override
  _i18.StreamQueryStore get streamQueries =>
      (super.noSuchMethod(
            Invocation.getter(#streamQueries),
            returnValue: _FakeStreamQueryStore_35(
              this,
              Invocation.getter(#streamQueries),
            ),
          )
          as _i18.StreamQueryStore);

  @override
  _i3.DatabaseConnectionUser get resolvedEngine =>
      (super.noSuchMethod(
            Invocation.getter(#resolvedEngine),
            returnValue: _FakeDatabaseConnectionUser_36(
              this,
              Invocation.getter(#resolvedEngine),
            ),
          )
          as _i3.DatabaseConnectionUser);

  @override
  _i4.$OrganizationsTable get organizations =>
      (super.noSuchMethod(
            Invocation.getter(#organizations),
            returnValue: _Fake$OrganizationsTable_4(
              this,
              Invocation.getter(#organizations),
            ),
          )
          as _i4.$OrganizationsTable);

  @override
  _i5.OrganizationsDaoManager get managers =>
      (super.noSuchMethod(
            Invocation.getter(#managers),
            returnValue: _FakeOrganizationsDaoManager_49(
              this,
              Invocation.getter(#managers),
            ),
          )
          as _i5.OrganizationsDaoManager);

  @override
  _i19.Future<List<_i4.Organization>> getAllOrganizations({
    int? limit,
    int? offset = 0,
    String? type,
    bool? isActive,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAllOrganizations, [], {
              #limit: limit,
              #offset: offset,
              #type: type,
              #isActive: isActive,
            }),
            returnValue: _i19.Future<List<_i4.Organization>>.value(
              <_i4.Organization>[],
            ),
          )
          as _i19.Future<List<_i4.Organization>>);

  @override
  _i19.Future<int> getOrganizationCount({String? type, bool? isActive}) =>
      (super.noSuchMethod(
            Invocation.method(#getOrganizationCount, [], {
              #type: type,
              #isActive: isActive,
            }),
            returnValue: _i19.Future<int>.value(0),
          )
          as _i19.Future<int>);

  @override
  _i19.Stream<List<_i4.Organization>> watchAllOrganizations({
    int? limit = 50,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchAllOrganizations, [], {
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i19.Stream<List<_i4.Organization>>.empty(),
          )
          as _i19.Stream<List<_i4.Organization>>);

  @override
  _i19.Future<int> insertOrganization(
    _i4.OrganizationsCompanion? organization,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#insertOrganization, [organization]),
            returnValue: _i19.Future<int>.value(0),
          )
          as _i19.Future<int>);

  @override
  _i19.Future<void> insertOrganizations(
    List<_i4.OrganizationsCompanion>? organizationsList,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#insertOrganizations, [organizationsList]),
            returnValue: _i19.Future<void>.value(),
            returnValueForMissingStub: _i19.Future<void>.value(),
          )
          as _i19.Future<void>);

  @override
  _i19.Future<bool> updateOrganization(_i4.Organization? organization) =>
      (super.noSuchMethod(
            Invocation.method(#updateOrganization, [organization]),
            returnValue: _i19.Future<bool>.value(false),
          )
          as _i19.Future<bool>);

  @override
  _i19.Future<_i4.Organization?> getOrganizationById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getOrganizationById, [id]),
            returnValue: _i19.Future<_i4.Organization?>.value(),
          )
          as _i19.Future<_i4.Organization?>);

  @override
  _i19.Future<_i4.Organization?> getOrganizationByName(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#getOrganizationByName, [name]),
            returnValue: _i19.Future<_i4.Organization?>.value(),
          )
          as _i19.Future<_i4.Organization?>);

  @override
  _i19.Future<List<_i4.Organization>> getOrganizationsByType(
    String? type, {
    bool? isActive,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getOrganizationsByType,
              [type],
              {#isActive: isActive},
            ),
            returnValue: _i19.Future<List<_i4.Organization>>.value(
              <_i4.Organization>[],
            ),
          )
          as _i19.Future<List<_i4.Organization>>);

  @override
  _i19.Future<bool> deactivateOrganization(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deactivateOrganization, [id]),
            returnValue: _i19.Future<bool>.value(false),
          )
          as _i19.Future<bool>);

  @override
  _i19.Future<bool> reactivateOrganization(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#reactivateOrganization, [id]),
            returnValue: _i19.Future<bool>.value(false),
          )
          as _i19.Future<bool>);

  @override
  _i19.Future<List<_i4.Organization>> getAllCommissaries({
    int? limit,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAllCommissaries, [], {
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i19.Future<List<_i4.Organization>>.value(
              <_i4.Organization>[],
            ),
          )
          as _i19.Future<List<_i4.Organization>>);

  @override
  _i19.Future<_i4.Organization?> getMainCommissary() =>
      (super.noSuchMethod(
            Invocation.method(#getMainCommissary, []),
            returnValue: _i19.Future<_i4.Organization?>.value(),
          )
          as _i19.Future<_i4.Organization?>);

  @override
  _i19.Future<List<_i4.Organization>> getAllFranchisees({
    int? limit,
    int? offset = 0,
    int? parentCommissaryId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAllFranchisees, [], {
              #limit: limit,
              #offset: offset,
              #parentCommissaryId: parentCommissaryId,
            }),
            returnValue: _i19.Future<List<_i4.Organization>>.value(
              <_i4.Organization>[],
            ),
          )
          as _i19.Future<List<_i4.Organization>>);

  @override
  _i19.Future<List<_i4.Organization>> getFranchiseesByCommissary(
    int? commissaryId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getFranchiseesByCommissary, [commissaryId]),
            returnValue: _i19.Future<List<_i4.Organization>>.value(
              <_i4.Organization>[],
            ),
          )
          as _i19.Future<List<_i4.Organization>>);

  @override
  _i19.Future<int> getFranchiseeCount(int? commissaryId) =>
      (super.noSuchMethod(
            Invocation.method(#getFranchiseeCount, [commissaryId]),
            returnValue: _i19.Future<int>.value(0),
          )
          as _i19.Future<int>);

  @override
  _i19.Future<List<_i4.Organization>> getUnsyncedOrganizations({
    int? limit = 100,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUnsyncedOrganizations, [], {
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i19.Future<List<_i4.Organization>>.value(
              <_i4.Organization>[],
            ),
          )
          as _i19.Future<List<_i4.Organization>>);

  @override
  _i19.Future<int> getUnsyncedOrganizationCount() =>
      (super.noSuchMethod(
            Invocation.method(#getUnsyncedOrganizationCount, []),
            returnValue: _i19.Future<int>.value(0),
          )
          as _i19.Future<int>);

  @override
  _i19.Future<void> markAsSynced(
    List<int>? organizationIds, {
    Map<int, String>? cloudIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #markAsSynced,
              [organizationIds],
              {#cloudIds: cloudIds},
            ),
            returnValue: _i19.Future<void>.value(),
            returnValueForMissingStub: _i19.Future<void>.value(),
          )
          as _i19.Future<void>);

  @override
  _i19.Future<void> upsertBatchFromCloud(
    List<Map<String, dynamic>>? cloudOrganizations,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#upsertBatchFromCloud, [cloudOrganizations]),
            returnValue: _i19.Future<void>.value(),
            returnValueForMissingStub: _i19.Future<void>.value(),
          )
          as _i19.Future<void>);

  @override
  _i19.Future<void> upsertFromCloud({
    required int? id,
    required String? name,
    required String? type,
    int? parentCommissaryId,
    String? contactPerson,
    String? phone,
    String? email,
    String? address,
    required bool? isActive,
    required DateTime? createdAt,
    required DateTime? lastUpdated,
    required String? cloudId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#upsertFromCloud, [], {
              #id: id,
              #name: name,
              #type: type,
              #parentCommissaryId: parentCommissaryId,
              #contactPerson: contactPerson,
              #phone: phone,
              #email: email,
              #address: address,
              #isActive: isActive,
              #createdAt: createdAt,
              #lastUpdated: lastUpdated,
              #cloudId: cloudId,
            }),
            returnValue: _i19.Future<void>.value(),
            returnValueForMissingStub: _i19.Future<void>.value(),
          )
          as _i19.Future<void>);

  @override
  _i19.Future<_i4.Organization?> getOrganizationByCloudId(String? cloudId) =>
      (super.noSuchMethod(
            Invocation.method(#getOrganizationByCloudId, [cloudId]),
            returnValue: _i19.Future<_i4.Organization?>.value(),
          )
          as _i19.Future<_i4.Organization?>);

  @override
  _i19.Stream<T> createStream<T extends Object>(
    _i18.QueryStreamFetcher<T>? stmt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createStream, [stmt]),
            returnValue: _i19.Stream<T>.empty(),
          )
          as _i19.Stream<T>);

  @override
  T alias<T, D>(_i3.ResultSetImplementation<T, D>? table, String? alias) =>
      (super.noSuchMethod(
            Invocation.method(#alias, [table, alias]),
            returnValue: _i21.dummyValue<T>(
              this,
              Invocation.method(#alias, [table, alias]),
            ),
          )
          as T);

  @override
  void markTablesUpdated(Iterable<_i3.TableInfo<_i3.Table, dynamic>>? tables) =>
      super.noSuchMethod(
        Invocation.method(#markTablesUpdated, [tables]),
        returnValueForMissingStub: null,
      );

  @override
  void notifyUpdates(Set<_i3.TableUpdate>? updates) => super.noSuchMethod(
    Invocation.method(#notifyUpdates, [updates]),
    returnValueForMissingStub: null,
  );

  @override
  _i19.Stream<Set<_i3.TableUpdate>> tableUpdates([
    _i3.TableUpdateQuery? query = const _i3.TableUpdateQuery.any(),
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#tableUpdates, [query]),
            returnValue: _i19.Stream<Set<_i3.TableUpdate>>.empty(),
          )
          as _i19.Stream<Set<_i3.TableUpdate>>);

  @override
  _i19.Future<T> doWhenOpened<T>(
    _i19.FutureOr<T> Function(_i3.QueryExecutor)? fn,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#doWhenOpened, [fn]),
            returnValue:
                _i21.ifNotNull(
                  _i21.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#doWhenOpened, [fn]),
                  ),
                  (T v) => _i19.Future<T>.value(v),
                ) ??
                _FakeFuture_37<T>(this, Invocation.method(#doWhenOpened, [fn])),
          )
          as _i19.Future<T>);

  @override
  _i3.InsertStatement<T, D> into<T extends _i3.Table, D>(
    _i3.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#into, [table]),
            returnValue: _FakeInsertStatement_39<T, D>(
              this,
              Invocation.method(#into, [table]),
            ),
          )
          as _i3.InsertStatement<T, D>);

  @override
  _i3.UpdateStatement<Tbl, R> update<Tbl extends _i3.Table, R>(
    _i3.TableInfo<Tbl, R>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [table]),
            returnValue: _FakeUpdateStatement_40<Tbl, R>(
              this,
              Invocation.method(#update, [table]),
            ),
          )
          as _i3.UpdateStatement<Tbl, R>);

  @override
  _i3.SimpleSelectStatement<T, R> select<T extends _i3.HasResultSet, R>(
    _i3.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#select, [table], {#distinct: distinct}),
            returnValue: _FakeSimpleSelectStatement_41<T, R>(
              this,
              Invocation.method(#select, [table], {#distinct: distinct}),
            ),
          )
          as _i3.SimpleSelectStatement<T, R>);

  @override
  _i3.JoinedSelectStatement<T, R> selectOnly<T extends _i3.HasResultSet, R>(
    _i3.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            returnValue: _FakeJoinedSelectStatement_42<T, R>(
              this,
              Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            ),
          )
          as _i3.JoinedSelectStatement<T, R>);

  @override
  _i3.BaseSelectStatement<_i3.TypedResult> selectExpressions(
    Iterable<_i3.Expression<Object>>? columns,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#selectExpressions, [columns]),
            returnValue: _FakeBaseSelectStatement_43<_i3.TypedResult>(
              this,
              Invocation.method(#selectExpressions, [columns]),
            ),
          )
          as _i3.BaseSelectStatement<_i3.TypedResult>);

  @override
  _i3.DeleteStatement<T, D> delete<T extends _i3.Table, D>(
    _i3.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [table]),
            returnValue: _FakeDeleteStatement_44<T, D>(
              this,
              Invocation.method(#delete, [table]),
            ),
          )
          as _i3.DeleteStatement<T, D>);

  @override
  _i19.Future<int> customUpdate(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i3.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customUpdate,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i19.Future<int>.value(0),
          )
          as _i19.Future<int>);

  @override
  _i19.Future<int> customInsert(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customInsert,
              [query],
              {#variables: variables, #updates: updates},
            ),
            returnValue: _i19.Future<int>.value(0),
          )
          as _i19.Future<int>);

  @override
  _i19.Future<List<_i3.QueryRow>> customWriteReturning(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i3.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customWriteReturning,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i19.Future<List<_i3.QueryRow>>.value(
              <_i3.QueryRow>[],
            ),
          )
          as _i19.Future<List<_i3.QueryRow>>);

  @override
  _i3.Selectable<_i3.QueryRow> customSelect(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelect,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_45<_i3.QueryRow>(
              this,
              Invocation.method(
                #customSelect,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i3.Selectable<_i3.QueryRow>);

  @override
  _i3.Selectable<_i3.QueryRow> customSelectQuery(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelectQuery,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_45<_i3.QueryRow>(
              this,
              Invocation.method(
                #customSelectQuery,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i3.Selectable<_i3.QueryRow>);

  @override
  _i19.Future<void> customStatement(String? statement, [List<dynamic>? args]) =>
      (super.noSuchMethod(
            Invocation.method(#customStatement, [statement, args]),
            returnValue: _i19.Future<void>.value(),
            returnValueForMissingStub: _i19.Future<void>.value(),
          )
          as _i19.Future<void>);

  @override
  _i19.Future<T> transaction<T>(
    _i19.Future<T> Function()? action, {
    bool? requireNew = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #transaction,
              [action],
              {#requireNew: requireNew},
            ),
            returnValue:
                _i21.ifNotNull(
                  _i21.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #transaction,
                      [action],
                      {#requireNew: requireNew},
                    ),
                  ),
                  (T v) => _i19.Future<T>.value(v),
                ) ??
                _FakeFuture_37<T>(
                  this,
                  Invocation.method(
                    #transaction,
                    [action],
                    {#requireNew: requireNew},
                  ),
                ),
          )
          as _i19.Future<T>);

  @override
  _i19.Future<T> exclusively<T>(_i19.Future<T> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#exclusively, [action]),
            returnValue:
                _i21.ifNotNull(
                  _i21.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#exclusively, [action]),
                  ),
                  (T v) => _i19.Future<T>.value(v),
                ) ??
                _FakeFuture_37<T>(
                  this,
                  Invocation.method(#exclusively, [action]),
                ),
          )
          as _i19.Future<T>);

  @override
  _i19.Future<void> batch(
    _i19.FutureOr<void> Function(_i3.Batch)? runInBatch,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#batch, [runInBatch]),
            returnValue: _i19.Future<void>.value(),
            returnValueForMissingStub: _i19.Future<void>.value(),
          )
          as _i19.Future<void>);

  @override
  _i19.Future<T> runWithInterceptor<T>(
    _i19.Future<T> Function()? action, {
    required _i3.QueryInterceptor? interceptor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #runWithInterceptor,
              [action],
              {#interceptor: interceptor},
            ),
            returnValue:
                _i21.ifNotNull(
                  _i21.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #runWithInterceptor,
                      [action],
                      {#interceptor: interceptor},
                    ),
                  ),
                  (T v) => _i19.Future<T>.value(v),
                ) ??
                _FakeFuture_37<T>(
                  this,
                  Invocation.method(
                    #runWithInterceptor,
                    [action],
                    {#interceptor: interceptor},
                  ),
                ),
          )
          as _i19.Future<T>);

  @override
  _i3.GenerationContext $write(
    _i3.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$write,
              [component],
              {#hasMultipleTables: hasMultipleTables, #startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_46(
              this,
              Invocation.method(
                #$write,
                [component],
                {
                  #hasMultipleTables: hasMultipleTables,
                  #startIndex: startIndex,
                },
              ),
            ),
          )
          as _i3.GenerationContext);

  @override
  _i3.GenerationContext $writeInsertable(
    _i3.TableInfo<_i3.Table, dynamic>? table,
    _i3.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$writeInsertable,
              [table, insertable],
              {#startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_46(
              this,
              Invocation.method(
                #$writeInsertable,
                [table, insertable],
                {#startIndex: startIndex},
              ),
            ),
          )
          as _i3.GenerationContext);

  @override
  String $expandVar(int? start, int? amount) =>
      (super.noSuchMethod(
            Invocation.method(#$expandVar, [start, amount]),
            returnValue: _i21.dummyValue<String>(
              this,
              Invocation.method(#$expandVar, [start, amount]),
            ),
          )
          as String);

  @override
  _i19.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i19.Future<void>.value(),
            returnValueForMissingStub: _i19.Future<void>.value(),
          )
          as _i19.Future<void>);
}

/// A class which mocks [RealtimeStockRequestService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRealtimeStockRequestService extends _i1.Mock
    implements _i23.RealtimeStockRequestService {
  MockRealtimeStockRequestService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i20.SupabaseClient get supabase =>
      (super.noSuchMethod(
            Invocation.getter(#supabase),
            returnValue: _FakeSupabaseClient_48(
              this,
              Invocation.getter(#supabase),
            ),
          )
          as _i20.SupabaseClient);

  @override
  _i4.AppDatabase get db =>
      (super.noSuchMethod(
            Invocation.getter(#db),
            returnValue: _FakeAppDatabase_47(this, Invocation.getter(#db)),
          )
          as _i4.AppDatabase);

  @override
  _i19.Stream<_i23.RealtimeConnectionStatus> get statusStream =>
      (super.noSuchMethod(
            Invocation.getter(#statusStream),
            returnValue: _i19.Stream<_i23.RealtimeConnectionStatus>.empty(),
          )
          as _i19.Stream<_i23.RealtimeConnectionStatus>);

  @override
  _i19.Stream<_i23.StockRequestEvent> get eventStream =>
      (super.noSuchMethod(
            Invocation.getter(#eventStream),
            returnValue: _i19.Stream<_i23.StockRequestEvent>.empty(),
          )
          as _i19.Stream<_i23.StockRequestEvent>);

  @override
  _i23.RealtimeConnectionStatus get status =>
      (super.noSuchMethod(
            Invocation.getter(#status),
            returnValue: _i23.RealtimeConnectionStatus.disconnected,
          )
          as _i23.RealtimeConnectionStatus);

  @override
  bool get isListening =>
      (super.noSuchMethod(Invocation.getter(#isListening), returnValue: false)
          as bool);

  @override
  int get activeScreenCount =>
      (super.noSuchMethod(Invocation.getter(#activeScreenCount), returnValue: 0)
          as int);

  @override
  set onRequestStatusChanged(dynamic Function(_i23.StockRequestEvent)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onRequestStatusChanged, value),
        returnValueForMissingStub: null,
      );

  @override
  set onConnectionStatusChanged(
    dynamic Function(_i23.RealtimeConnectionStatus)? value,
  ) => super.noSuchMethod(
    Invocation.setter(#onConnectionStatusChanged, value),
    returnValueForMissingStub: null,
  );

  @override
  set onError(dynamic Function(String)? value) => super.noSuchMethod(
    Invocation.setter(#onError, value),
    returnValueForMissingStub: null,
  );

  @override
  set syncCallback(_i19.Future<void> Function()? value) => super.noSuchMethod(
    Invocation.setter(#syncCallback, value),
    returnValueForMissingStub: null,
  );

  @override
  _i19.Future<void> attach(String? franchiseeCloudId) =>
      (super.noSuchMethod(
            Invocation.method(#attach, [franchiseeCloudId]),
            returnValue: _i19.Future<void>.value(),
            returnValueForMissingStub: _i19.Future<void>.value(),
          )
          as _i19.Future<void>);

  @override
  _i19.Future<void> detach() =>
      (super.noSuchMethod(
            Invocation.method(#detach, []),
            returnValue: _i19.Future<void>.value(),
            returnValueForMissingStub: _i19.Future<void>.value(),
          )
          as _i19.Future<void>);

  @override
  _i19.Future<void> pause() =>
      (super.noSuchMethod(
            Invocation.method(#pause, []),
            returnValue: _i19.Future<void>.value(),
            returnValueForMissingStub: _i19.Future<void>.value(),
          )
          as _i19.Future<void>);

  @override
  _i19.Future<void> resume() =>
      (super.noSuchMethod(
            Invocation.method(#resume, []),
            returnValue: _i19.Future<void>.value(),
            returnValueForMissingStub: _i19.Future<void>.value(),
          )
          as _i19.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
