// Mocks generated by Mockito 5.4.6 from annotations
// in chickenjoo_inventory/test/main_test_final.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i18;

import 'package:chickenjoo_inventory/database/app_database.dart' as _i3;
import 'package:chickenjoo_inventory/database/daos/branch_ingredient_stock_dao.dart'
    as _i11;
import 'package:chickenjoo_inventory/database/daos/branch_item_stock_dao.dart'
    as _i12;
import 'package:chickenjoo_inventory/database/daos/categories_dao.dart' as _i5;
import 'package:chickenjoo_inventory/database/daos/daily_sales_summary_dao.dart'
    as _i15;
import 'package:chickenjoo_inventory/database/daos/ingredients_dao.dart' as _i9;
import 'package:chickenjoo_inventory/database/daos/items_dao.dart' as _i8;
import 'package:chickenjoo_inventory/database/daos/organizations_dao.dart'
    as _i4;
import 'package:chickenjoo_inventory/database/daos/recipe_ingredients_dao.dart'
    as _i10;
import 'package:chickenjoo_inventory/database/daos/roles_dao.dart' as _i6;
import 'package:chickenjoo_inventory/database/daos/stock_change_requests_dao.dart'
    as _i14;
import 'package:chickenjoo_inventory/database/daos/stock_replenishment_requests_dao.dart'
    as _i13;
import 'package:chickenjoo_inventory/database/daos/sync_conflicts_dao.dart'
    as _i16;
import 'package:chickenjoo_inventory/database/daos/users_dao.dart' as _i7;
import 'package:chickenjoo_inventory/services/realtime_stock_request_service.dart'
    as _i23;
import 'package:chickenjoo_inventory/services/supabase_auth_service.dart'
    as _i20;
import 'package:chickenjoo_inventory/services/supabase_sync_service_v2.dart'
    as _i22;
import 'package:drift/drift.dart' as _i2;
import 'package:drift/src/runtime/executor/stream_queries.dart' as _i17;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i21;
import 'package:supabase_flutter/supabase_flutter.dart' as _i19;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMigrationStrategy_0 extends _i1.SmartFake
    implements _i2.MigrationStrategy {
  _FakeMigrationStrategy_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$AppDatabaseManager_1 extends _i1.SmartFake
    implements _i3.$AppDatabaseManager {
  _Fake$AppDatabaseManager_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$OrganizationsTable_2 extends _i1.SmartFake
    implements _i3.$OrganizationsTable {
  _Fake$OrganizationsTable_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$CategoriesTable_3 extends _i1.SmartFake
    implements _i3.$CategoriesTable {
  _Fake$CategoriesTable_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$RolesTable_4 extends _i1.SmartFake implements _i3.$RolesTable {
  _Fake$RolesTable_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$UsersTable_5 extends _i1.SmartFake implements _i3.$UsersTable {
  _Fake$UsersTable_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$ItemsTable_6 extends _i1.SmartFake implements _i3.$ItemsTable {
  _Fake$ItemsTable_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$IngredientsTable_7 extends _i1.SmartFake
    implements _i3.$IngredientsTable {
  _Fake$IngredientsTable_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$RecipeIngredientsTable_8 extends _i1.SmartFake
    implements _i3.$RecipeIngredientsTable {
  _Fake$RecipeIngredientsTable_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$BranchIngredientStockTable_9 extends _i1.SmartFake
    implements _i3.$BranchIngredientStockTable {
  _Fake$BranchIngredientStockTable_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$BranchItemStockTable_10 extends _i1.SmartFake
    implements _i3.$BranchItemStockTable {
  _Fake$BranchItemStockTable_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$StockReplenishmentRequestsTable_11 extends _i1.SmartFake
    implements _i3.$StockReplenishmentRequestsTable {
  _Fake$StockReplenishmentRequestsTable_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _Fake$StockChangeRequestsTable_12 extends _i1.SmartFake
    implements _i3.$StockChangeRequestsTable {
  _Fake$StockChangeRequestsTable_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$DailySalesSummaryTable_13 extends _i1.SmartFake
    implements _i3.$DailySalesSummaryTable {
  _Fake$DailySalesSummaryTable_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$SyncConflictsTable_14 extends _i1.SmartFake
    implements _i3.$SyncConflictsTable {
  _Fake$SyncConflictsTable_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrganizationsDao_15 extends _i1.SmartFake
    implements _i4.OrganizationsDao {
  _FakeOrganizationsDao_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCategoriesDao_16 extends _i1.SmartFake implements _i5.CategoriesDao {
  _FakeCategoriesDao_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRolesDao_17 extends _i1.SmartFake implements _i6.RolesDao {
  _FakeRolesDao_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUsersDao_18 extends _i1.SmartFake implements _i7.UsersDao {
  _FakeUsersDao_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeItemsDao_19 extends _i1.SmartFake implements _i8.ItemsDao {
  _FakeItemsDao_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIngredientsDao_20 extends _i1.SmartFake
    implements _i9.IngredientsDao {
  _FakeIngredientsDao_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRecipeIngredientsDao_21 extends _i1.SmartFake
    implements _i10.RecipeIngredientsDao {
  _FakeRecipeIngredientsDao_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBranchIngredientStockDao_22 extends _i1.SmartFake
    implements _i11.BranchIngredientStockDao {
  _FakeBranchIngredientStockDao_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBranchItemStockDao_23 extends _i1.SmartFake
    implements _i12.BranchItemStockDao {
  _FakeBranchItemStockDao_23(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStockReplenishmentRequestsDao_24 extends _i1.SmartFake
    implements _i13.StockReplenishmentRequestsDao {
  _FakeStockReplenishmentRequestsDao_24(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeStockChangeRequestsDao_25 extends _i1.SmartFake
    implements _i14.StockChangeRequestsDao {
  _FakeStockChangeRequestsDao_25(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDailySalesSummaryDao_26 extends _i1.SmartFake
    implements _i15.DailySalesSummaryDao {
  _FakeDailySalesSummaryDao_26(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSyncConflictsDao_27 extends _i1.SmartFake
    implements _i16.SyncConflictsDao {
  _FakeSyncConflictsDao_27(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamQueryUpdateRules_28 extends _i1.SmartFake
    implements _i2.StreamQueryUpdateRules {
  _FakeStreamQueryUpdateRules_28(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGeneratedDatabase_29 extends _i1.SmartFake
    implements _i2.GeneratedDatabase {
  _FakeGeneratedDatabase_29(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDriftDatabaseOptions_30 extends _i1.SmartFake
    implements _i2.DriftDatabaseOptions {
  _FakeDriftDatabaseOptions_30(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnection_31 extends _i1.SmartFake
    implements _i2.DatabaseConnection {
  _FakeDatabaseConnection_31(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQueryExecutor_32 extends _i1.SmartFake implements _i2.QueryExecutor {
  _FakeQueryExecutor_32(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamQueryStore_33 extends _i1.SmartFake
    implements _i17.StreamQueryStore {
  _FakeStreamQueryStore_33(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnectionUser_34 extends _i1.SmartFake
    implements _i2.DatabaseConnectionUser {
  _FakeDatabaseConnectionUser_34(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_35<T1> extends _i1.SmartFake implements _i18.Future<T1> {
  _FakeFuture_35(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMigrator_36 extends _i1.SmartFake implements _i2.Migrator {
  _FakeMigrator_36(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInsertStatement_37<T1 extends _i2.Table, D1> extends _i1.SmartFake
    implements _i2.InsertStatement<T1, D1> {
  _FakeInsertStatement_37(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateStatement_38<T extends _i2.Table, D> extends _i1.SmartFake
    implements _i2.UpdateStatement<T, D> {
  _FakeUpdateStatement_38(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSimpleSelectStatement_39<T1 extends _i2.HasResultSet, D>
    extends _i1.SmartFake
    implements _i2.SimpleSelectStatement<T1, D> {
  _FakeSimpleSelectStatement_39(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeJoinedSelectStatement_40<FirstT extends _i2.HasResultSet, FirstD>
    extends _i1.SmartFake
    implements _i2.JoinedSelectStatement<FirstT, FirstD> {
  _FakeJoinedSelectStatement_40(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseSelectStatement_41<Row> extends _i1.SmartFake
    implements _i2.BaseSelectStatement<Row> {
  _FakeBaseSelectStatement_41(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeleteStatement_42<T1 extends _i2.Table, D1> extends _i1.SmartFake
    implements _i2.DeleteStatement<T1, D1> {
  _FakeDeleteStatement_42(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSelectable_43<T> extends _i1.SmartFake implements _i2.Selectable<T> {
  _FakeSelectable_43(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGenerationContext_44 extends _i1.SmartFake
    implements _i2.GenerationContext {
  _FakeGenerationContext_44(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAppDatabase_45 extends _i1.SmartFake implements _i3.AppDatabase {
  _FakeAppDatabase_45(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseClient_46 extends _i1.SmartFake
    implements _i19.SupabaseClient {
  _FakeSupabaseClient_46(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthResult_47 extends _i1.SmartFake implements _i20.AuthResult {
  _FakeAuthResult_47(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AppDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppDatabase extends _i1.Mock implements _i3.AppDatabase {
  MockAppDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get schemaVersion =>
      (super.noSuchMethod(Invocation.getter(#schemaVersion), returnValue: 0)
          as int);

  @override
  _i2.MigrationStrategy get migration =>
      (super.noSuchMethod(
            Invocation.getter(#migration),
            returnValue: _FakeMigrationStrategy_0(
              this,
              Invocation.getter(#migration),
            ),
          )
          as _i2.MigrationStrategy);

  @override
  _i3.$AppDatabaseManager get managers =>
      (super.noSuchMethod(
            Invocation.getter(#managers),
            returnValue: _Fake$AppDatabaseManager_1(
              this,
              Invocation.getter(#managers),
            ),
          )
          as _i3.$AppDatabaseManager);

  @override
  _i3.$OrganizationsTable get organizations =>
      (super.noSuchMethod(
            Invocation.getter(#organizations),
            returnValue: _Fake$OrganizationsTable_2(
              this,
              Invocation.getter(#organizations),
            ),
          )
          as _i3.$OrganizationsTable);

  @override
  _i3.$CategoriesTable get categories =>
      (super.noSuchMethod(
            Invocation.getter(#categories),
            returnValue: _Fake$CategoriesTable_3(
              this,
              Invocation.getter(#categories),
            ),
          )
          as _i3.$CategoriesTable);

  @override
  _i3.$RolesTable get roles =>
      (super.noSuchMethod(
            Invocation.getter(#roles),
            returnValue: _Fake$RolesTable_4(this, Invocation.getter(#roles)),
          )
          as _i3.$RolesTable);

  @override
  _i3.$UsersTable get users =>
      (super.noSuchMethod(
            Invocation.getter(#users),
            returnValue: _Fake$UsersTable_5(this, Invocation.getter(#users)),
          )
          as _i3.$UsersTable);

  @override
  _i3.$ItemsTable get items =>
      (super.noSuchMethod(
            Invocation.getter(#items),
            returnValue: _Fake$ItemsTable_6(this, Invocation.getter(#items)),
          )
          as _i3.$ItemsTable);

  @override
  _i3.$IngredientsTable get ingredients =>
      (super.noSuchMethod(
            Invocation.getter(#ingredients),
            returnValue: _Fake$IngredientsTable_7(
              this,
              Invocation.getter(#ingredients),
            ),
          )
          as _i3.$IngredientsTable);

  @override
  _i3.$RecipeIngredientsTable get recipeIngredients =>
      (super.noSuchMethod(
            Invocation.getter(#recipeIngredients),
            returnValue: _Fake$RecipeIngredientsTable_8(
              this,
              Invocation.getter(#recipeIngredients),
            ),
          )
          as _i3.$RecipeIngredientsTable);

  @override
  _i3.$BranchIngredientStockTable get branchIngredientStock =>
      (super.noSuchMethod(
            Invocation.getter(#branchIngredientStock),
            returnValue: _Fake$BranchIngredientStockTable_9(
              this,
              Invocation.getter(#branchIngredientStock),
            ),
          )
          as _i3.$BranchIngredientStockTable);

  @override
  _i3.$BranchItemStockTable get branchItemStock =>
      (super.noSuchMethod(
            Invocation.getter(#branchItemStock),
            returnValue: _Fake$BranchItemStockTable_10(
              this,
              Invocation.getter(#branchItemStock),
            ),
          )
          as _i3.$BranchItemStockTable);

  @override
  _i3.$StockReplenishmentRequestsTable get stockReplenishmentRequests =>
      (super.noSuchMethod(
            Invocation.getter(#stockReplenishmentRequests),
            returnValue: _Fake$StockReplenishmentRequestsTable_11(
              this,
              Invocation.getter(#stockReplenishmentRequests),
            ),
          )
          as _i3.$StockReplenishmentRequestsTable);

  @override
  _i3.$StockChangeRequestsTable get stockChangeRequests =>
      (super.noSuchMethod(
            Invocation.getter(#stockChangeRequests),
            returnValue: _Fake$StockChangeRequestsTable_12(
              this,
              Invocation.getter(#stockChangeRequests),
            ),
          )
          as _i3.$StockChangeRequestsTable);

  @override
  _i3.$DailySalesSummaryTable get dailySalesSummary =>
      (super.noSuchMethod(
            Invocation.getter(#dailySalesSummary),
            returnValue: _Fake$DailySalesSummaryTable_13(
              this,
              Invocation.getter(#dailySalesSummary),
            ),
          )
          as _i3.$DailySalesSummaryTable);

  @override
  _i3.$SyncConflictsTable get syncConflicts =>
      (super.noSuchMethod(
            Invocation.getter(#syncConflicts),
            returnValue: _Fake$SyncConflictsTable_14(
              this,
              Invocation.getter(#syncConflicts),
            ),
          )
          as _i3.$SyncConflictsTable);

  @override
  _i4.OrganizationsDao get organizationsDao =>
      (super.noSuchMethod(
            Invocation.getter(#organizationsDao),
            returnValue: _FakeOrganizationsDao_15(
              this,
              Invocation.getter(#organizationsDao),
            ),
          )
          as _i4.OrganizationsDao);

  @override
  _i5.CategoriesDao get categoriesDao =>
      (super.noSuchMethod(
            Invocation.getter(#categoriesDao),
            returnValue: _FakeCategoriesDao_16(
              this,
              Invocation.getter(#categoriesDao),
            ),
          )
          as _i5.CategoriesDao);

  @override
  _i6.RolesDao get rolesDao =>
      (super.noSuchMethod(
            Invocation.getter(#rolesDao),
            returnValue: _FakeRolesDao_17(this, Invocation.getter(#rolesDao)),
          )
          as _i6.RolesDao);

  @override
  _i7.UsersDao get usersDao =>
      (super.noSuchMethod(
            Invocation.getter(#usersDao),
            returnValue: _FakeUsersDao_18(this, Invocation.getter(#usersDao)),
          )
          as _i7.UsersDao);

  @override
  _i8.ItemsDao get itemsDao =>
      (super.noSuchMethod(
            Invocation.getter(#itemsDao),
            returnValue: _FakeItemsDao_19(this, Invocation.getter(#itemsDao)),
          )
          as _i8.ItemsDao);

  @override
  _i9.IngredientsDao get ingredientsDao =>
      (super.noSuchMethod(
            Invocation.getter(#ingredientsDao),
            returnValue: _FakeIngredientsDao_20(
              this,
              Invocation.getter(#ingredientsDao),
            ),
          )
          as _i9.IngredientsDao);

  @override
  _i10.RecipeIngredientsDao get recipeIngredientsDao =>
      (super.noSuchMethod(
            Invocation.getter(#recipeIngredientsDao),
            returnValue: _FakeRecipeIngredientsDao_21(
              this,
              Invocation.getter(#recipeIngredientsDao),
            ),
          )
          as _i10.RecipeIngredientsDao);

  @override
  _i11.BranchIngredientStockDao get branchIngredientStockDao =>
      (super.noSuchMethod(
            Invocation.getter(#branchIngredientStockDao),
            returnValue: _FakeBranchIngredientStockDao_22(
              this,
              Invocation.getter(#branchIngredientStockDao),
            ),
          )
          as _i11.BranchIngredientStockDao);

  @override
  _i12.BranchItemStockDao get branchItemStockDao =>
      (super.noSuchMethod(
            Invocation.getter(#branchItemStockDao),
            returnValue: _FakeBranchItemStockDao_23(
              this,
              Invocation.getter(#branchItemStockDao),
            ),
          )
          as _i12.BranchItemStockDao);

  @override
  _i13.StockReplenishmentRequestsDao get stockReplenishmentRequestsDao =>
      (super.noSuchMethod(
            Invocation.getter(#stockReplenishmentRequestsDao),
            returnValue: _FakeStockReplenishmentRequestsDao_24(
              this,
              Invocation.getter(#stockReplenishmentRequestsDao),
            ),
          )
          as _i13.StockReplenishmentRequestsDao);

  @override
  _i14.StockChangeRequestsDao get stockChangeRequestsDao =>
      (super.noSuchMethod(
            Invocation.getter(#stockChangeRequestsDao),
            returnValue: _FakeStockChangeRequestsDao_25(
              this,
              Invocation.getter(#stockChangeRequestsDao),
            ),
          )
          as _i14.StockChangeRequestsDao);

  @override
  _i15.DailySalesSummaryDao get dailySalesSummaryDao =>
      (super.noSuchMethod(
            Invocation.getter(#dailySalesSummaryDao),
            returnValue: _FakeDailySalesSummaryDao_26(
              this,
              Invocation.getter(#dailySalesSummaryDao),
            ),
          )
          as _i15.DailySalesSummaryDao);

  @override
  _i16.SyncConflictsDao get syncConflictsDao =>
      (super.noSuchMethod(
            Invocation.getter(#syncConflictsDao),
            returnValue: _FakeSyncConflictsDao_27(
              this,
              Invocation.getter(#syncConflictsDao),
            ),
          )
          as _i16.SyncConflictsDao);

  @override
  Iterable<_i2.TableInfo<_i2.Table, Object?>> get allTables =>
      (super.noSuchMethod(
            Invocation.getter(#allTables),
            returnValue: <_i2.TableInfo<_i2.Table, Object?>>[],
          )
          as Iterable<_i2.TableInfo<_i2.Table, Object?>>);

  @override
  List<_i2.DatabaseSchemaEntity> get allSchemaEntities =>
      (super.noSuchMethod(
            Invocation.getter(#allSchemaEntities),
            returnValue: <_i2.DatabaseSchemaEntity>[],
          )
          as List<_i2.DatabaseSchemaEntity>);

  @override
  _i2.StreamQueryUpdateRules get streamUpdateRules =>
      (super.noSuchMethod(
            Invocation.getter(#streamUpdateRules),
            returnValue: _FakeStreamQueryUpdateRules_28(
              this,
              Invocation.getter(#streamUpdateRules),
            ),
          )
          as _i2.StreamQueryUpdateRules);

  @override
  _i2.GeneratedDatabase get attachedDatabase =>
      (super.noSuchMethod(
            Invocation.getter(#attachedDatabase),
            returnValue: _FakeGeneratedDatabase_29(
              this,
              Invocation.getter(#attachedDatabase),
            ),
          )
          as _i2.GeneratedDatabase);

  @override
  _i2.DriftDatabaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeDriftDatabaseOptions_30(
              this,
              Invocation.getter(#options),
            ),
          )
          as _i2.DriftDatabaseOptions);

  @override
  _i2.DatabaseConnection get connection =>
      (super.noSuchMethod(
            Invocation.getter(#connection),
            returnValue: _FakeDatabaseConnection_31(
              this,
              Invocation.getter(#connection),
            ),
          )
          as _i2.DatabaseConnection);

  @override
  _i2.SqlTypes get typeMapping =>
      (super.noSuchMethod(
            Invocation.getter(#typeMapping),
            returnValue: _i21.dummyValue<_i2.SqlTypes>(
              this,
              Invocation.getter(#typeMapping),
            ),
          )
          as _i2.SqlTypes);

  @override
  _i2.QueryExecutor get executor =>
      (super.noSuchMethod(
            Invocation.getter(#executor),
            returnValue: _FakeQueryExecutor_32(
              this,
              Invocation.getter(#executor),
            ),
          )
          as _i2.QueryExecutor);

  @override
  _i17.StreamQueryStore get streamQueries =>
      (super.noSuchMethod(
            Invocation.getter(#streamQueries),
            returnValue: _FakeStreamQueryStore_33(
              this,
              Invocation.getter(#streamQueries),
            ),
          )
          as _i17.StreamQueryStore);

  @override
  _i2.DatabaseConnectionUser get resolvedEngine =>
      (super.noSuchMethod(
            Invocation.getter(#resolvedEngine),
            returnValue: _FakeDatabaseConnectionUser_34(
              this,
              Invocation.getter(#resolvedEngine),
            ),
          )
          as _i2.DatabaseConnectionUser);

  @override
  _i18.Future<T> executeInTransaction<T>(_i18.Future<T> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#executeInTransaction, [action]),
            returnValue:
                _i21.ifNotNull(
                  _i21.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#executeInTransaction, [action]),
                  ),
                  (T v) => _i18.Future<T>.value(v),
                ) ??
                _FakeFuture_35<T>(
                  this,
                  Invocation.method(#executeInTransaction, [action]),
                ),
          )
          as _i18.Future<T>);

  @override
  _i2.Migrator createMigrator() =>
      (super.noSuchMethod(
            Invocation.method(#createMigrator, []),
            returnValue: _FakeMigrator_36(
              this,
              Invocation.method(#createMigrator, []),
            ),
          )
          as _i2.Migrator);

  @override
  _i18.Future<void> beforeOpen(
    _i2.QueryExecutor? executor,
    _i2.OpeningDetails? details,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#beforeOpen, [executor, details]),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<Ret> computeWithDatabase<Ret, DB extends _i2.GeneratedDatabase>({
    required _i18.FutureOr<Ret> Function(DB)? computation,
    required DB Function(_i2.DatabaseConnection)? connect,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#computeWithDatabase, [], {
              #computation: computation,
              #connect: connect,
            }),
            returnValue:
                _i21.ifNotNull(
                  _i21.dummyValueOrNull<Ret>(
                    this,
                    Invocation.method(#computeWithDatabase, [], {
                      #computation: computation,
                      #connect: connect,
                    }),
                  ),
                  (Ret v) => _i18.Future<Ret>.value(v),
                ) ??
                _FakeFuture_35<Ret>(
                  this,
                  Invocation.method(#computeWithDatabase, [], {
                    #computation: computation,
                    #connect: connect,
                  }),
                ),
          )
          as _i18.Future<Ret>);

  @override
  _i18.Stream<T> createStream<T extends Object>(
    _i17.QueryStreamFetcher<T>? stmt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createStream, [stmt]),
            returnValue: _i18.Stream<T>.empty(),
          )
          as _i18.Stream<T>);

  @override
  T alias<T, D>(_i2.ResultSetImplementation<T, D>? table, String? alias) =>
      (super.noSuchMethod(
            Invocation.method(#alias, [table, alias]),
            returnValue: _i21.dummyValue<T>(
              this,
              Invocation.method(#alias, [table, alias]),
            ),
          )
          as T);

  @override
  void markTablesUpdated(Iterable<_i2.TableInfo<_i2.Table, dynamic>>? tables) =>
      super.noSuchMethod(
        Invocation.method(#markTablesUpdated, [tables]),
        returnValueForMissingStub: null,
      );

  @override
  void notifyUpdates(Set<_i2.TableUpdate>? updates) => super.noSuchMethod(
    Invocation.method(#notifyUpdates, [updates]),
    returnValueForMissingStub: null,
  );

  @override
  _i18.Stream<Set<_i2.TableUpdate>> tableUpdates([
    _i2.TableUpdateQuery? query = const _i2.TableUpdateQuery.any(),
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#tableUpdates, [query]),
            returnValue: _i18.Stream<Set<_i2.TableUpdate>>.empty(),
          )
          as _i18.Stream<Set<_i2.TableUpdate>>);

  @override
  _i18.Future<T> doWhenOpened<T>(
    _i18.FutureOr<T> Function(_i2.QueryExecutor)? fn,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#doWhenOpened, [fn]),
            returnValue:
                _i21.ifNotNull(
                  _i21.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#doWhenOpened, [fn]),
                  ),
                  (T v) => _i18.Future<T>.value(v),
                ) ??
                _FakeFuture_35<T>(this, Invocation.method(#doWhenOpened, [fn])),
          )
          as _i18.Future<T>);

  @override
  _i2.InsertStatement<T, D> into<T extends _i2.Table, D>(
    _i2.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#into, [table]),
            returnValue: _FakeInsertStatement_37<T, D>(
              this,
              Invocation.method(#into, [table]),
            ),
          )
          as _i2.InsertStatement<T, D>);

  @override
  _i2.UpdateStatement<Tbl, R> update<Tbl extends _i2.Table, R>(
    _i2.TableInfo<Tbl, R>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [table]),
            returnValue: _FakeUpdateStatement_38<Tbl, R>(
              this,
              Invocation.method(#update, [table]),
            ),
          )
          as _i2.UpdateStatement<Tbl, R>);

  @override
  _i2.SimpleSelectStatement<T, R> select<T extends _i2.HasResultSet, R>(
    _i2.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#select, [table], {#distinct: distinct}),
            returnValue: _FakeSimpleSelectStatement_39<T, R>(
              this,
              Invocation.method(#select, [table], {#distinct: distinct}),
            ),
          )
          as _i2.SimpleSelectStatement<T, R>);

  @override
  _i2.JoinedSelectStatement<T, R> selectOnly<T extends _i2.HasResultSet, R>(
    _i2.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            returnValue: _FakeJoinedSelectStatement_40<T, R>(
              this,
              Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            ),
          )
          as _i2.JoinedSelectStatement<T, R>);

  @override
  _i2.BaseSelectStatement<_i2.TypedResult> selectExpressions(
    Iterable<_i2.Expression<Object>>? columns,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#selectExpressions, [columns]),
            returnValue: _FakeBaseSelectStatement_41<_i2.TypedResult>(
              this,
              Invocation.method(#selectExpressions, [columns]),
            ),
          )
          as _i2.BaseSelectStatement<_i2.TypedResult>);

  @override
  _i2.DeleteStatement<T, D> delete<T extends _i2.Table, D>(
    _i2.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [table]),
            returnValue: _FakeDeleteStatement_42<T, D>(
              this,
              Invocation.method(#delete, [table]),
            ),
          )
          as _i2.DeleteStatement<T, D>);

  @override
  _i18.Future<int> customUpdate(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i2.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customUpdate,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i18.Future<int>.value(0),
          )
          as _i18.Future<int>);

  @override
  _i18.Future<int> customInsert(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? updates,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customInsert,
              [query],
              {#variables: variables, #updates: updates},
            ),
            returnValue: _i18.Future<int>.value(0),
          )
          as _i18.Future<int>);

  @override
  _i18.Future<List<_i2.QueryRow>> customWriteReturning(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i2.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customWriteReturning,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i18.Future<List<_i2.QueryRow>>.value(
              <_i2.QueryRow>[],
            ),
          )
          as _i18.Future<List<_i2.QueryRow>>);

  @override
  _i2.Selectable<_i2.QueryRow> customSelect(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelect,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_43<_i2.QueryRow>(
              this,
              Invocation.method(
                #customSelect,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i2.Selectable<_i2.QueryRow>);

  @override
  _i2.Selectable<_i2.QueryRow> customSelectQuery(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelectQuery,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_43<_i2.QueryRow>(
              this,
              Invocation.method(
                #customSelectQuery,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i2.Selectable<_i2.QueryRow>);

  @override
  _i18.Future<void> customStatement(String? statement, [List<dynamic>? args]) =>
      (super.noSuchMethod(
            Invocation.method(#customStatement, [statement, args]),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<T> transaction<T>(
    _i18.Future<T> Function()? action, {
    bool? requireNew = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #transaction,
              [action],
              {#requireNew: requireNew},
            ),
            returnValue:
                _i21.ifNotNull(
                  _i21.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #transaction,
                      [action],
                      {#requireNew: requireNew},
                    ),
                  ),
                  (T v) => _i18.Future<T>.value(v),
                ) ??
                _FakeFuture_35<T>(
                  this,
                  Invocation.method(
                    #transaction,
                    [action],
                    {#requireNew: requireNew},
                  ),
                ),
          )
          as _i18.Future<T>);

  @override
  _i18.Future<T> exclusively<T>(_i18.Future<T> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#exclusively, [action]),
            returnValue:
                _i21.ifNotNull(
                  _i21.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#exclusively, [action]),
                  ),
                  (T v) => _i18.Future<T>.value(v),
                ) ??
                _FakeFuture_35<T>(
                  this,
                  Invocation.method(#exclusively, [action]),
                ),
          )
          as _i18.Future<T>);

  @override
  _i18.Future<void> batch(
    _i18.FutureOr<void> Function(_i2.Batch)? runInBatch,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#batch, [runInBatch]),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<T> runWithInterceptor<T>(
    _i18.Future<T> Function()? action, {
    required _i2.QueryInterceptor? interceptor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #runWithInterceptor,
              [action],
              {#interceptor: interceptor},
            ),
            returnValue:
                _i21.ifNotNull(
                  _i21.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #runWithInterceptor,
                      [action],
                      {#interceptor: interceptor},
                    ),
                  ),
                  (T v) => _i18.Future<T>.value(v),
                ) ??
                _FakeFuture_35<T>(
                  this,
                  Invocation.method(
                    #runWithInterceptor,
                    [action],
                    {#interceptor: interceptor},
                  ),
                ),
          )
          as _i18.Future<T>);

  @override
  _i2.GenerationContext $write(
    _i2.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$write,
              [component],
              {#hasMultipleTables: hasMultipleTables, #startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_44(
              this,
              Invocation.method(
                #$write,
                [component],
                {
                  #hasMultipleTables: hasMultipleTables,
                  #startIndex: startIndex,
                },
              ),
            ),
          )
          as _i2.GenerationContext);

  @override
  _i2.GenerationContext $writeInsertable(
    _i2.TableInfo<_i2.Table, dynamic>? table,
    _i2.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$writeInsertable,
              [table, insertable],
              {#startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_44(
              this,
              Invocation.method(
                #$writeInsertable,
                [table, insertable],
                {#startIndex: startIndex},
              ),
            ),
          )
          as _i2.GenerationContext);

  @override
  String $expandVar(int? start, int? amount) =>
      (super.noSuchMethod(
            Invocation.method(#$expandVar, [start, amount]),
            returnValue: _i21.dummyValue<String>(
              this,
              Invocation.method(#$expandVar, [start, amount]),
            ),
          )
          as String);
}

/// A class which mocks [SupabaseSyncServiceV2].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseSyncServiceV2 extends _i1.Mock
    implements _i22.SupabaseSyncServiceV2 {
  MockSupabaseSyncServiceV2() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.AppDatabase get db =>
      (super.noSuchMethod(
            Invocation.getter(#db),
            returnValue: _FakeAppDatabase_45(this, Invocation.getter(#db)),
          )
          as _i3.AppDatabase);

  @override
  _i19.SupabaseClient get supabase =>
      (super.noSuchMethod(
            Invocation.getter(#supabase),
            returnValue: _FakeSupabaseClient_46(
              this,
              Invocation.getter(#supabase),
            ),
          )
          as _i19.SupabaseClient);

  @override
  bool get canSync =>
      (super.noSuchMethod(Invocation.getter(#canSync), returnValue: false)
          as bool);

  @override
  set onConnectivityChanged(dynamic Function(bool)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onConnectivityChanged, value),
        returnValueForMissingStub: null,
      );

  @override
  set onSyncStatusChanged(dynamic Function(String)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onSyncStatusChanged, value),
        returnValueForMissingStub: null,
      );

  @override
  set onSyncError(dynamic Function(String)? value) => super.noSuchMethod(
    Invocation.setter(#onSyncError, value),
    returnValueForMissingStub: null,
  );

  @override
  set onSyncProgress(dynamic Function(double, String)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onSyncProgress, value),
        returnValueForMissingStub: null,
      );

  @override
  set onSyncComplete(dynamic Function()? value) => super.noSuchMethod(
    Invocation.setter(#onSyncComplete, value),
    returnValueForMissingStub: null,
  );

  @override
  set onConflictDetected(dynamic Function(String, String)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onConflictDetected, value),
        returnValueForMissingStub: null,
      );

  @override
  _i18.Future<void> initialize({
    int? organizationId,
    String? organizationCloudId,
    String? organizationType,
    int? parentCommissaryId,
    String? parentCommissaryCloudId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [], {
              #organizationId: organizationId,
              #organizationCloudId: organizationCloudId,
              #organizationType: organizationType,
              #parentCommissaryId: parentCommissaryId,
              #parentCommissaryCloudId: parentCommissaryCloudId,
            }),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  void startPeriodicSync() => super.noSuchMethod(
    Invocation.method(#startPeriodicSync, []),
    returnValueForMissingStub: null,
  );

  @override
  void stopPeriodicSync() => super.noSuchMethod(
    Invocation.method(#stopPeriodicSync, []),
    returnValueForMissingStub: null,
  );

  @override
  _i18.Future<void> syncAll() =>
      (super.noSuchMethod(
            Invocation.method(#syncAll, []),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<void> forceFullSyncReplenishmentRequests() =>
      (super.noSuchMethod(
            Invocation.method(#forceFullSyncReplenishmentRequests, []),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<void> syncImmediate() =>
      (super.noSuchMethod(
            Invocation.method(#syncImmediate, []),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<void> syncItemsOnly() =>
      (super.noSuchMethod(
            Invocation.method(#syncItemsOnly, []),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<void> syncOrganizations() =>
      (super.noSuchMethod(
            Invocation.method(#syncOrganizations, []),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<void> syncRoles() =>
      (super.noSuchMethod(
            Invocation.method(#syncRoles, []),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<void> syncUsers() =>
      (super.noSuchMethod(
            Invocation.method(#syncUsers, []),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<void> syncItems() =>
      (super.noSuchMethod(
            Invocation.method(#syncItems, []),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<void> syncIngredients() =>
      (super.noSuchMethod(
            Invocation.method(#syncIngredients, []),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<void> syncRecipeIngredients() =>
      (super.noSuchMethod(
            Invocation.method(#syncRecipeIngredients, []),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<void> syncStockReplenishmentRequests() =>
      (super.noSuchMethod(
            Invocation.method(#syncStockReplenishmentRequests, []),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<void> syncStockChangeRequests() =>
      (super.noSuchMethod(
            Invocation.method(#syncStockChangeRequests, []),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<void> syncBranchItemStock() =>
      (super.noSuchMethod(
            Invocation.method(#syncBranchItemStock, []),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<void> syncBranchIngredientStock() =>
      (super.noSuchMethod(
            Invocation.method(#syncBranchIngredientStock, []),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<void> syncDailySalesSummary() =>
      (super.noSuchMethod(
            Invocation.method(#syncDailySalesSummary, []),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<Map<String, dynamic>> getSyncStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getSyncStatus, []),
            returnValue: _i18.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i18.Future<Map<String, dynamic>>);

  @override
  void setOrganizationContext({
    required int? organizationId,
    required String? organizationType,
    int? parentCommissaryId,
  }) => super.noSuchMethod(
    Invocation.method(#setOrganizationContext, [], {
      #organizationId: organizationId,
      #organizationType: organizationType,
      #parentCommissaryId: parentCommissaryId,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void clearOrganizationContext() => super.noSuchMethod(
    Invocation.method(#clearOrganizationContext, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SupabaseAuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseAuthService extends _i1.Mock
    implements _i20.SupabaseAuthService {
  MockSupabaseAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  bool get isCommissary =>
      (super.noSuchMethod(Invocation.getter(#isCommissary), returnValue: false)
          as bool);

  @override
  bool get isFranchisee =>
      (super.noSuchMethod(Invocation.getter(#isFranchisee), returnValue: false)
          as bool);

  @override
  _i18.Stream<_i20.UserData?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i18.Stream<_i20.UserData?>.empty(),
          )
          as _i18.Stream<_i20.UserData?>);

  @override
  _i20.AuthLifecycleState get lifecycleState =>
      (super.noSuchMethod(
            Invocation.getter(#lifecycleState),
            returnValue: _i20.AuthLifecycleState.bootstrapping,
          )
          as _i20.AuthLifecycleState);

  @override
  _i18.Stream<_i20.AuthLifecycleState> get lifecycleStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#lifecycleStateChanges),
            returnValue: _i18.Stream<_i20.AuthLifecycleState>.empty(),
          )
          as _i18.Stream<_i20.AuthLifecycleState>);

  @override
  _i18.Future<void> get bootstrapComplete =>
      (super.noSuchMethod(
            Invocation.getter(#bootstrapComplete),
            returnValue: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<_i20.AuthLifecycleState> bootstrap() =>
      (super.noSuchMethod(
            Invocation.method(#bootstrap, []),
            returnValue: _i18.Future<_i20.AuthLifecycleState>.value(
              _i20.AuthLifecycleState.bootstrapping,
            ),
          )
          as _i18.Future<_i20.AuthLifecycleState>);

  @override
  _i18.Future<_i20.AuthResult> signUp({
    required String? email,
    required String? password,
    required String? username,
    required String? fullName,
    required int? organizationId,
    required int? roleId,
    String? phone,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {
              #email: email,
              #password: password,
              #username: username,
              #fullName: fullName,
              #organizationId: organizationId,
              #roleId: roleId,
              #phone: phone,
            }),
            returnValue: _i18.Future<_i20.AuthResult>.value(
              _FakeAuthResult_47(
                this,
                Invocation.method(#signUp, [], {
                  #email: email,
                  #password: password,
                  #username: username,
                  #fullName: fullName,
                  #organizationId: organizationId,
                  #roleId: roleId,
                  #phone: phone,
                }),
              ),
            ),
          )
          as _i18.Future<_i20.AuthResult>);

  @override
  _i18.Future<_i20.AuthResult> signIn({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i18.Future<_i20.AuthResult>.value(
              _FakeAuthResult_47(
                this,
                Invocation.method(#signIn, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i18.Future<_i20.AuthResult>);

  @override
  _i18.Future<_i20.AuthResult> createEmployee({
    required String? email,
    required String? username,
    required String? password,
    required int? organizationId,
    required int? roleId,
    String? fullName,
    String? phone,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createEmployee, [], {
              #email: email,
              #username: username,
              #password: password,
              #organizationId: organizationId,
              #roleId: roleId,
              #fullName: fullName,
              #phone: phone,
            }),
            returnValue: _i18.Future<_i20.AuthResult>.value(
              _FakeAuthResult_47(
                this,
                Invocation.method(#createEmployee, [], {
                  #email: email,
                  #username: username,
                  #password: password,
                  #organizationId: organizationId,
                  #roleId: roleId,
                  #fullName: fullName,
                  #phone: phone,
                }),
              ),
            ),
          )
          as _i18.Future<_i20.AuthResult>);

  @override
  _i18.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<_i20.AuthResult> resetPassword(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [email]),
            returnValue: _i18.Future<_i20.AuthResult>.value(
              _FakeAuthResult_47(
                this,
                Invocation.method(#resetPassword, [email]),
              ),
            ),
          )
          as _i18.Future<_i20.AuthResult>);

  @override
  _i18.Future<_i20.AuthResult> updatePassword(String? newPassword) =>
      (super.noSuchMethod(
            Invocation.method(#updatePassword, [newPassword]),
            returnValue: _i18.Future<_i20.AuthResult>.value(
              _FakeAuthResult_47(
                this,
                Invocation.method(#updatePassword, [newPassword]),
              ),
            ),
          )
          as _i18.Future<_i20.AuthResult>);

  @override
  _i18.Future<_i20.AuthResult> restoreSession() =>
      (super.noSuchMethod(
            Invocation.method(#restoreSession, []),
            returnValue: _i18.Future<_i20.AuthResult>.value(
              _FakeAuthResult_47(this, Invocation.method(#restoreSession, [])),
            ),
          )
          as _i18.Future<_i20.AuthResult>);

  @override
  _i18.Future<void> refreshSession() =>
      (super.noSuchMethod(
            Invocation.method(#refreshSession, []),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<({List<Map<String, dynamic>> branches, bool isOffline})>
  fetchAvailableBranches() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAvailableBranches, []),
            returnValue:
                _i18.Future<
                  ({List<Map<String, dynamic>> branches, bool isOffline})
                >.value((branches: <Map<String, dynamic>>[], isOffline: false)),
          )
          as _i18.Future<
            ({List<Map<String, dynamic>> branches, bool isOffline})
          >);

  @override
  _i18.Future<_i20.AuthResult> signInToBranch({
    required String? email,
    required String? password,
    required String? branchCloudId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInToBranch, [], {
              #email: email,
              #password: password,
              #branchCloudId: branchCloudId,
            }),
            returnValue: _i18.Future<_i20.AuthResult>.value(
              _FakeAuthResult_47(
                this,
                Invocation.method(#signInToBranch, [], {
                  #email: email,
                  #password: password,
                  #branchCloudId: branchCloudId,
                }),
              ),
            ),
          )
          as _i18.Future<_i20.AuthResult>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [RealtimeStockRequestService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRealtimeStockRequestService extends _i1.Mock
    implements _i23.RealtimeStockRequestService {
  MockRealtimeStockRequestService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i19.SupabaseClient get supabase =>
      (super.noSuchMethod(
            Invocation.getter(#supabase),
            returnValue: _FakeSupabaseClient_46(
              this,
              Invocation.getter(#supabase),
            ),
          )
          as _i19.SupabaseClient);

  @override
  _i3.AppDatabase get db =>
      (super.noSuchMethod(
            Invocation.getter(#db),
            returnValue: _FakeAppDatabase_45(this, Invocation.getter(#db)),
          )
          as _i3.AppDatabase);

  @override
  _i18.Stream<_i23.RealtimeConnectionStatus> get statusStream =>
      (super.noSuchMethod(
            Invocation.getter(#statusStream),
            returnValue: _i18.Stream<_i23.RealtimeConnectionStatus>.empty(),
          )
          as _i18.Stream<_i23.RealtimeConnectionStatus>);

  @override
  _i18.Stream<_i23.StockRequestEvent> get eventStream =>
      (super.noSuchMethod(
            Invocation.getter(#eventStream),
            returnValue: _i18.Stream<_i23.StockRequestEvent>.empty(),
          )
          as _i18.Stream<_i23.StockRequestEvent>);

  @override
  _i23.RealtimeConnectionStatus get status =>
      (super.noSuchMethod(
            Invocation.getter(#status),
            returnValue: _i23.RealtimeConnectionStatus.disconnected,
          )
          as _i23.RealtimeConnectionStatus);

  @override
  bool get isListening =>
      (super.noSuchMethod(Invocation.getter(#isListening), returnValue: false)
          as bool);

  @override
  int get activeScreenCount =>
      (super.noSuchMethod(Invocation.getter(#activeScreenCount), returnValue: 0)
          as int);

  @override
  set onRequestStatusChanged(dynamic Function(_i23.StockRequestEvent)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onRequestStatusChanged, value),
        returnValueForMissingStub: null,
      );

  @override
  set onConnectionStatusChanged(
    dynamic Function(_i23.RealtimeConnectionStatus)? value,
  ) => super.noSuchMethod(
    Invocation.setter(#onConnectionStatusChanged, value),
    returnValueForMissingStub: null,
  );

  @override
  set onError(dynamic Function(String)? value) => super.noSuchMethod(
    Invocation.setter(#onError, value),
    returnValueForMissingStub: null,
  );

  @override
  set syncCallback(_i18.Future<void> Function()? value) => super.noSuchMethod(
    Invocation.setter(#syncCallback, value),
    returnValueForMissingStub: null,
  );

  @override
  _i18.Future<void> attach(String? franchiseeCloudId) =>
      (super.noSuchMethod(
            Invocation.method(#attach, [franchiseeCloudId]),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<void> detach() =>
      (super.noSuchMethod(
            Invocation.method(#detach, []),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<void> pause() =>
      (super.noSuchMethod(
            Invocation.method(#pause, []),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<void> resume() =>
      (super.noSuchMethod(
            Invocation.method(#resume, []),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
