name: chickenjoo_inventory
version: 1.0.0+1
publish_to: 'none'
description: "A new Flutter project."

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  drift: ^2.29.0
  sqlite3_flutter_libs: ^0.5.40
  collection: ^1.18.2
  path: ^1.9.0
  path_provider: ^2.1.5

  #CLOUD
  shared_preferences: ^2.1.1
  connectivity_plus: ^5.0.2
  supabase_flutter: ^2.3.4
  flutter_dotenv: ^5.1.0
  battery_plus: ^6.0.3

  #SECURITY
  uuid: ^4.0.0  
  crypto: ^3.0.3 

  #LOGGING
  logger: ^2.0.2

  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.29.0
  build_runner: ^2.4.11
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/chicken_joo_logo.png
    - .env
