// Mocks generated by Mockito 5.4.6 from annotations
// in chickenjoo_inventory/test/models/item_with_category_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:chickenjoo_inventory/database/app_database.dart' as _i2;
import 'package:drift/drift.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDateTime_0 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeItemsCompanion_1 extends _i1.SmartFake
    implements _i2.ItemsCompanion {
  _FakeItemsCompanion_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeItem_2 extends _i1.SmartFake implements _i2.Item {
  _FakeItem_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCategoriesCompanion_3 extends _i1.SmartFake
    implements _i2.CategoriesCompanion {
  _FakeCategoriesCompanion_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCategory_4 extends _i1.SmartFake implements _i2.Category {
  _FakeCategory_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [Item].
///
/// See the documentation for Mockito's code generation for more information.
class MockItem extends _i1.Mock implements _i2.Item {
  MockItem() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get id =>
      (super.noSuchMethod(Invocation.getter(#id), returnValue: 0) as int);

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i3.dummyValue<String>(this, Invocation.getter(#name)),
          )
          as String);

  @override
  int get organizationId =>
      (super.noSuchMethod(Invocation.getter(#organizationId), returnValue: 0)
          as int);

  @override
  int get stock =>
      (super.noSuchMethod(Invocation.getter(#stock), returnValue: 0) as int);

  @override
  int get sold =>
      (super.noSuchMethod(Invocation.getter(#sold), returnValue: 0) as int);

  @override
  int get spoilage =>
      (super.noSuchMethod(Invocation.getter(#spoilage), returnValue: 0) as int);

  @override
  String get unit =>
      (super.noSuchMethod(
            Invocation.getter(#unit),
            returnValue: _i3.dummyValue<String>(this, Invocation.getter(#unit)),
          )
          as String);

  @override
  DateTime get createdAt =>
      (super.noSuchMethod(
            Invocation.getter(#createdAt),
            returnValue: _FakeDateTime_0(this, Invocation.getter(#createdAt)),
          )
          as DateTime);

  @override
  DateTime get lastUpdated =>
      (super.noSuchMethod(
            Invocation.getter(#lastUpdated),
            returnValue: _FakeDateTime_0(this, Invocation.getter(#lastUpdated)),
          )
          as DateTime);

  @override
  bool get isDeleted =>
      (super.noSuchMethod(Invocation.getter(#isDeleted), returnValue: false)
          as bool);

  @override
  bool get isSynced =>
      (super.noSuchMethod(Invocation.getter(#isSynced), returnValue: false)
          as bool);

  @override
  Map<String, _i4.Expression<Object>> toColumns(bool? nullToAbsent) =>
      (super.noSuchMethod(
            Invocation.method(#toColumns, [nullToAbsent]),
            returnValue: <String, _i4.Expression<Object>>{},
          )
          as Map<String, _i4.Expression<Object>>);

  @override
  _i2.ItemsCompanion toCompanion(bool? nullToAbsent) =>
      (super.noSuchMethod(
            Invocation.method(#toCompanion, [nullToAbsent]),
            returnValue: _FakeItemsCompanion_1(
              this,
              Invocation.method(#toCompanion, [nullToAbsent]),
            ),
          )
          as _i2.ItemsCompanion);

  @override
  Map<String, dynamic> toJson({_i4.ValueSerializer? serializer}) =>
      (super.noSuchMethod(
            Invocation.method(#toJson, [], {#serializer: serializer}),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i2.Item copyWith({
    int? id,
    String? name,
    _i4.Value<int?>? categoryId = const _i4.Value.absent(),
    int? organizationId,
    _i4.Value<int?>? masterItemId = const _i4.Value.absent(),
    int? stock,
    int? sold,
    int? spoilage,
    _i4.Value<double?>? price = const _i4.Value.absent(),
    _i4.Value<double?>? costPrice = const _i4.Value.absent(),
    String? unit,
    _i4.Value<int?>? minimumStock = const _i4.Value.absent(),
    _i4.Value<String?>? description = const _i4.Value.absent(),
    DateTime? createdAt,
    DateTime? lastUpdated,
    bool? isDeleted,
    bool? isSynced,
    _i4.Value<String?>? cloudId = const _i4.Value.absent(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#copyWith, [], {
              #id: id,
              #name: name,
              #categoryId: categoryId,
              #organizationId: organizationId,
              #masterItemId: masterItemId,
              #stock: stock,
              #sold: sold,
              #spoilage: spoilage,
              #price: price,
              #costPrice: costPrice,
              #unit: unit,
              #minimumStock: minimumStock,
              #description: description,
              #createdAt: createdAt,
              #lastUpdated: lastUpdated,
              #isDeleted: isDeleted,
              #isSynced: isSynced,
              #cloudId: cloudId,
            }),
            returnValue: _FakeItem_2(
              this,
              Invocation.method(#copyWith, [], {
                #id: id,
                #name: name,
                #categoryId: categoryId,
                #organizationId: organizationId,
                #masterItemId: masterItemId,
                #stock: stock,
                #sold: sold,
                #spoilage: spoilage,
                #price: price,
                #costPrice: costPrice,
                #unit: unit,
                #minimumStock: minimumStock,
                #description: description,
                #createdAt: createdAt,
                #lastUpdated: lastUpdated,
                #isDeleted: isDeleted,
                #isSynced: isSynced,
                #cloudId: cloudId,
              }),
            ),
          )
          as _i2.Item);

  @override
  _i2.Item copyWithCompanion(_i2.ItemsCompanion? data) =>
      (super.noSuchMethod(
            Invocation.method(#copyWithCompanion, [data]),
            returnValue: _FakeItem_2(
              this,
              Invocation.method(#copyWithCompanion, [data]),
            ),
          )
          as _i2.Item);

  @override
  String toJsonString({_i4.ValueSerializer? serializer}) =>
      (super.noSuchMethod(
            Invocation.method(#toJsonString, [], {#serializer: serializer}),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.method(#toJsonString, [], {#serializer: serializer}),
            ),
          )
          as String);
}

/// A class which mocks [Category].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategory extends _i1.Mock implements _i2.Category {
  MockCategory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get id =>
      (super.noSuchMethod(Invocation.getter(#id), returnValue: 0) as int);

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i3.dummyValue<String>(this, Invocation.getter(#name)),
          )
          as String);

  @override
  DateTime get createdAt =>
      (super.noSuchMethod(
            Invocation.getter(#createdAt),
            returnValue: _FakeDateTime_0(this, Invocation.getter(#createdAt)),
          )
          as DateTime);

  @override
  DateTime get lastUpdated =>
      (super.noSuchMethod(
            Invocation.getter(#lastUpdated),
            returnValue: _FakeDateTime_0(this, Invocation.getter(#lastUpdated)),
          )
          as DateTime);

  @override
  bool get isDeleted =>
      (super.noSuchMethod(Invocation.getter(#isDeleted), returnValue: false)
          as bool);

  @override
  Map<String, _i4.Expression<Object>> toColumns(bool? nullToAbsent) =>
      (super.noSuchMethod(
            Invocation.method(#toColumns, [nullToAbsent]),
            returnValue: <String, _i4.Expression<Object>>{},
          )
          as Map<String, _i4.Expression<Object>>);

  @override
  _i2.CategoriesCompanion toCompanion(bool? nullToAbsent) =>
      (super.noSuchMethod(
            Invocation.method(#toCompanion, [nullToAbsent]),
            returnValue: _FakeCategoriesCompanion_3(
              this,
              Invocation.method(#toCompanion, [nullToAbsent]),
            ),
          )
          as _i2.CategoriesCompanion);

  @override
  Map<String, dynamic> toJson({_i4.ValueSerializer? serializer}) =>
      (super.noSuchMethod(
            Invocation.method(#toJson, [], {#serializer: serializer}),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i2.Category copyWith({
    int? id,
    String? name,
    _i4.Value<String?>? description = const _i4.Value.absent(),
    DateTime? createdAt,
    DateTime? lastUpdated,
    bool? isDeleted,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#copyWith, [], {
              #id: id,
              #name: name,
              #description: description,
              #createdAt: createdAt,
              #lastUpdated: lastUpdated,
              #isDeleted: isDeleted,
            }),
            returnValue: _FakeCategory_4(
              this,
              Invocation.method(#copyWith, [], {
                #id: id,
                #name: name,
                #description: description,
                #createdAt: createdAt,
                #lastUpdated: lastUpdated,
                #isDeleted: isDeleted,
              }),
            ),
          )
          as _i2.Category);

  @override
  _i2.Category copyWithCompanion(_i2.CategoriesCompanion? data) =>
      (super.noSuchMethod(
            Invocation.method(#copyWithCompanion, [data]),
            returnValue: _FakeCategory_4(
              this,
              Invocation.method(#copyWithCompanion, [data]),
            ),
          )
          as _i2.Category);

  @override
  String toJsonString({_i4.ValueSerializer? serializer}) =>
      (super.noSuchMethod(
            Invocation.method(#toJsonString, [], {#serializer: serializer}),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.method(#toJsonString, [], {#serializer: serializer}),
            ),
          )
          as String);
}
