// Mocks generated by Mockito 5.4.6 from annotations
// in chickenjoo_inventory/test/services/realtime_sales_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i17;

import 'package:chickenjoo_inventory/database/app_database.dart' as _i4;
import 'package:chickenjoo_inventory/database/daos/branch_ingredient_stock_dao.dart'
    as _i12;
import 'package:chickenjoo_inventory/database/daos/categories_dao.dart' as _i6;
import 'package:chickenjoo_inventory/database/daos/daily_sales_summary_dao.dart'
    as _i15;
import 'package:chickenjoo_inventory/database/daos/ingredients_dao.dart'
    as _i10;
import 'package:chickenjoo_inventory/database/daos/items_dao.dart' as _i9;
import 'package:chickenjoo_inventory/database/daos/organizations_dao.dart'
    as _i5;
import 'package:chickenjoo_inventory/database/daos/recipe_ingredients_dao.dart'
    as _i11;
import 'package:chickenjoo_inventory/database/daos/roles_dao.dart' as _i7;
import 'package:chickenjoo_inventory/database/daos/stock_change_requests_dao.dart'
    as _i14;
import 'package:chickenjoo_inventory/database/daos/stock_replenishment_requests_dao.dart'
    as _i13;
import 'package:chickenjoo_inventory/database/daos/users_dao.dart' as _i8;
import 'package:drift/drift.dart' as _i3;
import 'package:drift/src/runtime/executor/stream_queries.dart' as _i16;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i18;
import 'package:supabase/supabase.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFunctionsClient_0 extends _i1.SmartFake
    implements _i2.FunctionsClient {
  _FakeFunctionsClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseStorageClient_1 extends _i1.SmartFake
    implements _i2.SupabaseStorageClient {
  _FakeSupabaseStorageClient_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRealtimeClient_2 extends _i1.SmartFake
    implements _i2.RealtimeClient {
  _FakeRealtimeClient_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostgrestClient_3 extends _i1.SmartFake
    implements _i2.PostgrestClient {
  _FakePostgrestClient_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoTrueClient_4 extends _i1.SmartFake implements _i2.GoTrueClient {
  _FakeGoTrueClient_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseQueryBuilder_5 extends _i1.SmartFake
    implements _i2.SupabaseQueryBuilder {
  _FakeSupabaseQueryBuilder_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseQuerySchema_6 extends _i1.SmartFake
    implements _i2.SupabaseQuerySchema {
  _FakeSupabaseQuerySchema_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostgrestFilterBuilder_7<T1> extends _i1.SmartFake
    implements _i2.PostgrestFilterBuilder<T1> {
  _FakePostgrestFilterBuilder_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRealtimeChannel_8 extends _i1.SmartFake
    implements _i2.RealtimeChannel {
  _FakeRealtimeChannel_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMigrationStrategy_9 extends _i1.SmartFake
    implements _i3.MigrationStrategy {
  _FakeMigrationStrategy_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$AppDatabaseManager_10 extends _i1.SmartFake
    implements _i4.$AppDatabaseManager {
  _Fake$AppDatabaseManager_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$OrganizationsTable_11 extends _i1.SmartFake
    implements _i4.$OrganizationsTable {
  _Fake$OrganizationsTable_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$CategoriesTable_12 extends _i1.SmartFake
    implements _i4.$CategoriesTable {
  _Fake$CategoriesTable_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$RolesTable_13 extends _i1.SmartFake implements _i4.$RolesTable {
  _Fake$RolesTable_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$UsersTable_14 extends _i1.SmartFake implements _i4.$UsersTable {
  _Fake$UsersTable_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$ItemsTable_15 extends _i1.SmartFake implements _i4.$ItemsTable {
  _Fake$ItemsTable_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$IngredientsTable_16 extends _i1.SmartFake
    implements _i4.$IngredientsTable {
  _Fake$IngredientsTable_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$RecipeIngredientsTable_17 extends _i1.SmartFake
    implements _i4.$RecipeIngredientsTable {
  _Fake$RecipeIngredientsTable_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$BranchIngredientStockTable_18 extends _i1.SmartFake
    implements _i4.$BranchIngredientStockTable {
  _Fake$BranchIngredientStockTable_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _Fake$StockReplenishmentRequestsTable_19 extends _i1.SmartFake
    implements _i4.$StockReplenishmentRequestsTable {
  _Fake$StockReplenishmentRequestsTable_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _Fake$StockChangeRequestsTable_20 extends _i1.SmartFake
    implements _i4.$StockChangeRequestsTable {
  _Fake$StockChangeRequestsTable_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$DailySalesSummaryTable_21 extends _i1.SmartFake
    implements _i4.$DailySalesSummaryTable {
  _Fake$DailySalesSummaryTable_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrganizationsDao_22 extends _i1.SmartFake
    implements _i5.OrganizationsDao {
  _FakeOrganizationsDao_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCategoriesDao_23 extends _i1.SmartFake implements _i6.CategoriesDao {
  _FakeCategoriesDao_23(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRolesDao_24 extends _i1.SmartFake implements _i7.RolesDao {
  _FakeRolesDao_24(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUsersDao_25 extends _i1.SmartFake implements _i8.UsersDao {
  _FakeUsersDao_25(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeItemsDao_26 extends _i1.SmartFake implements _i9.ItemsDao {
  _FakeItemsDao_26(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIngredientsDao_27 extends _i1.SmartFake
    implements _i10.IngredientsDao {
  _FakeIngredientsDao_27(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRecipeIngredientsDao_28 extends _i1.SmartFake
    implements _i11.RecipeIngredientsDao {
  _FakeRecipeIngredientsDao_28(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBranchIngredientStockDao_29 extends _i1.SmartFake
    implements _i12.BranchIngredientStockDao {
  _FakeBranchIngredientStockDao_29(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStockReplenishmentRequestsDao_30 extends _i1.SmartFake
    implements _i13.StockReplenishmentRequestsDao {
  _FakeStockReplenishmentRequestsDao_30(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeStockChangeRequestsDao_31 extends _i1.SmartFake
    implements _i14.StockChangeRequestsDao {
  _FakeStockChangeRequestsDao_31(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDailySalesSummaryDao_32 extends _i1.SmartFake
    implements _i15.DailySalesSummaryDao {
  _FakeDailySalesSummaryDao_32(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamQueryUpdateRules_33 extends _i1.SmartFake
    implements _i3.StreamQueryUpdateRules {
  _FakeStreamQueryUpdateRules_33(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGeneratedDatabase_34 extends _i1.SmartFake
    implements _i3.GeneratedDatabase {
  _FakeGeneratedDatabase_34(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDriftDatabaseOptions_35 extends _i1.SmartFake
    implements _i3.DriftDatabaseOptions {
  _FakeDriftDatabaseOptions_35(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnection_36 extends _i1.SmartFake
    implements _i3.DatabaseConnection {
  _FakeDatabaseConnection_36(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQueryExecutor_37 extends _i1.SmartFake implements _i3.QueryExecutor {
  _FakeQueryExecutor_37(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamQueryStore_38 extends _i1.SmartFake
    implements _i16.StreamQueryStore {
  _FakeStreamQueryStore_38(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnectionUser_39 extends _i1.SmartFake
    implements _i3.DatabaseConnectionUser {
  _FakeDatabaseConnectionUser_39(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_40<T1> extends _i1.SmartFake implements _i17.Future<T1> {
  _FakeFuture_40(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMigrator_41 extends _i1.SmartFake implements _i3.Migrator {
  _FakeMigrator_41(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInsertStatement_42<T1 extends _i3.Table, D1> extends _i1.SmartFake
    implements _i3.InsertStatement<T1, D1> {
  _FakeInsertStatement_42(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateStatement_43<T extends _i3.Table, D> extends _i1.SmartFake
    implements _i3.UpdateStatement<T, D> {
  _FakeUpdateStatement_43(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSimpleSelectStatement_44<T1 extends _i3.HasResultSet, D>
    extends _i1.SmartFake
    implements _i3.SimpleSelectStatement<T1, D> {
  _FakeSimpleSelectStatement_44(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeJoinedSelectStatement_45<FirstT extends _i3.HasResultSet, FirstD>
    extends _i1.SmartFake
    implements _i3.JoinedSelectStatement<FirstT, FirstD> {
  _FakeJoinedSelectStatement_45(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseSelectStatement_46<Row> extends _i1.SmartFake
    implements _i3.BaseSelectStatement<Row> {
  _FakeBaseSelectStatement_46(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeleteStatement_47<T1 extends _i3.Table, D1> extends _i1.SmartFake
    implements _i3.DeleteStatement<T1, D1> {
  _FakeDeleteStatement_47(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSelectable_48<T> extends _i1.SmartFake implements _i3.Selectable<T> {
  _FakeSelectable_48(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGenerationContext_49 extends _i1.SmartFake
    implements _i3.GenerationContext {
  _FakeGenerationContext_49(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SupabaseClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseClient extends _i1.Mock implements _i2.SupabaseClient {
  @override
  _i2.FunctionsClient get functions =>
      (super.noSuchMethod(
            Invocation.getter(#functions),
            returnValue: _FakeFunctionsClient_0(
              this,
              Invocation.getter(#functions),
            ),
            returnValueForMissingStub: _FakeFunctionsClient_0(
              this,
              Invocation.getter(#functions),
            ),
          )
          as _i2.FunctionsClient);

  @override
  _i2.SupabaseStorageClient get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeSupabaseStorageClient_1(
              this,
              Invocation.getter(#storage),
            ),
            returnValueForMissingStub: _FakeSupabaseStorageClient_1(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i2.SupabaseStorageClient);

  @override
  _i2.RealtimeClient get realtime =>
      (super.noSuchMethod(
            Invocation.getter(#realtime),
            returnValue: _FakeRealtimeClient_2(
              this,
              Invocation.getter(#realtime),
            ),
            returnValueForMissingStub: _FakeRealtimeClient_2(
              this,
              Invocation.getter(#realtime),
            ),
          )
          as _i2.RealtimeClient);

  @override
  _i2.PostgrestClient get rest =>
      (super.noSuchMethod(
            Invocation.getter(#rest),
            returnValue: _FakePostgrestClient_3(this, Invocation.getter(#rest)),
            returnValueForMissingStub: _FakePostgrestClient_3(
              this,
              Invocation.getter(#rest),
            ),
          )
          as _i2.PostgrestClient);

  @override
  Map<String, String> get headers =>
      (super.noSuchMethod(
            Invocation.getter(#headers),
            returnValue: <String, String>{},
            returnValueForMissingStub: <String, String>{},
          )
          as Map<String, String>);

  @override
  _i2.GoTrueClient get auth =>
      (super.noSuchMethod(
            Invocation.getter(#auth),
            returnValue: _FakeGoTrueClient_4(this, Invocation.getter(#auth)),
            returnValueForMissingStub: _FakeGoTrueClient_4(
              this,
              Invocation.getter(#auth),
            ),
          )
          as _i2.GoTrueClient);

  @override
  set functions(_i2.FunctionsClient? value) => super.noSuchMethod(
    Invocation.setter(#functions, value),
    returnValueForMissingStub: null,
  );

  @override
  set storage(_i2.SupabaseStorageClient? value) => super.noSuchMethod(
    Invocation.setter(#storage, value),
    returnValueForMissingStub: null,
  );

  @override
  set realtime(_i2.RealtimeClient? value) => super.noSuchMethod(
    Invocation.setter(#realtime, value),
    returnValueForMissingStub: null,
  );

  @override
  set rest(_i2.PostgrestClient? value) => super.noSuchMethod(
    Invocation.setter(#rest, value),
    returnValueForMissingStub: null,
  );

  @override
  set headers(Map<String, String>? headers) => super.noSuchMethod(
    Invocation.setter(#headers, headers),
    returnValueForMissingStub: null,
  );

  @override
  _i2.SupabaseQueryBuilder from(String? table) =>
      (super.noSuchMethod(
            Invocation.method(#from, [table]),
            returnValue: _FakeSupabaseQueryBuilder_5(
              this,
              Invocation.method(#from, [table]),
            ),
            returnValueForMissingStub: _FakeSupabaseQueryBuilder_5(
              this,
              Invocation.method(#from, [table]),
            ),
          )
          as _i2.SupabaseQueryBuilder);

  @override
  _i2.SupabaseQuerySchema schema(String? schema) =>
      (super.noSuchMethod(
            Invocation.method(#schema, [schema]),
            returnValue: _FakeSupabaseQuerySchema_6(
              this,
              Invocation.method(#schema, [schema]),
            ),
            returnValueForMissingStub: _FakeSupabaseQuerySchema_6(
              this,
              Invocation.method(#schema, [schema]),
            ),
          )
          as _i2.SupabaseQuerySchema);

  @override
  _i2.PostgrestFilterBuilder<T> rpc<T>(
    String? fn, {
    Map<String, dynamic>? params,
    dynamic get = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#rpc, [fn], {#params: params, #get: get}),
            returnValue: _FakePostgrestFilterBuilder_7<T>(
              this,
              Invocation.method(#rpc, [fn], {#params: params, #get: get}),
            ),
            returnValueForMissingStub: _FakePostgrestFilterBuilder_7<T>(
              this,
              Invocation.method(#rpc, [fn], {#params: params, #get: get}),
            ),
          )
          as _i2.PostgrestFilterBuilder<T>);

  @override
  _i2.RealtimeChannel channel(
    String? name, {
    _i2.RealtimeChannelConfig? opts = const _i2.RealtimeChannelConfig(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#channel, [name], {#opts: opts}),
            returnValue: _FakeRealtimeChannel_8(
              this,
              Invocation.method(#channel, [name], {#opts: opts}),
            ),
            returnValueForMissingStub: _FakeRealtimeChannel_8(
              this,
              Invocation.method(#channel, [name], {#opts: opts}),
            ),
          )
          as _i2.RealtimeChannel);

  @override
  List<_i2.RealtimeChannel> getChannels() =>
      (super.noSuchMethod(
            Invocation.method(#getChannels, []),
            returnValue: <_i2.RealtimeChannel>[],
            returnValueForMissingStub: <_i2.RealtimeChannel>[],
          )
          as List<_i2.RealtimeChannel>);

  @override
  _i17.Future<String> removeChannel(_i2.RealtimeChannel? channel) =>
      (super.noSuchMethod(
            Invocation.method(#removeChannel, [channel]),
            returnValue: _i17.Future<String>.value(
              _i18.dummyValue<String>(
                this,
                Invocation.method(#removeChannel, [channel]),
              ),
            ),
            returnValueForMissingStub: _i17.Future<String>.value(
              _i18.dummyValue<String>(
                this,
                Invocation.method(#removeChannel, [channel]),
              ),
            ),
          )
          as _i17.Future<String>);

  @override
  _i17.Future<List<String>> removeAllChannels() =>
      (super.noSuchMethod(
            Invocation.method(#removeAllChannels, []),
            returnValue: _i17.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i17.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i17.Future<List<String>>);

  @override
  _i17.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);
}

/// A class which mocks [AppDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppDatabase extends _i1.Mock implements _i4.AppDatabase {
  @override
  int get schemaVersion =>
      (super.noSuchMethod(
            Invocation.getter(#schemaVersion),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i3.MigrationStrategy get migration =>
      (super.noSuchMethod(
            Invocation.getter(#migration),
            returnValue: _FakeMigrationStrategy_9(
              this,
              Invocation.getter(#migration),
            ),
            returnValueForMissingStub: _FakeMigrationStrategy_9(
              this,
              Invocation.getter(#migration),
            ),
          )
          as _i3.MigrationStrategy);

  @override
  _i4.$AppDatabaseManager get managers =>
      (super.noSuchMethod(
            Invocation.getter(#managers),
            returnValue: _Fake$AppDatabaseManager_10(
              this,
              Invocation.getter(#managers),
            ),
            returnValueForMissingStub: _Fake$AppDatabaseManager_10(
              this,
              Invocation.getter(#managers),
            ),
          )
          as _i4.$AppDatabaseManager);

  @override
  _i4.$OrganizationsTable get organizations =>
      (super.noSuchMethod(
            Invocation.getter(#organizations),
            returnValue: _Fake$OrganizationsTable_11(
              this,
              Invocation.getter(#organizations),
            ),
            returnValueForMissingStub: _Fake$OrganizationsTable_11(
              this,
              Invocation.getter(#organizations),
            ),
          )
          as _i4.$OrganizationsTable);

  @override
  _i4.$CategoriesTable get categories =>
      (super.noSuchMethod(
            Invocation.getter(#categories),
            returnValue: _Fake$CategoriesTable_12(
              this,
              Invocation.getter(#categories),
            ),
            returnValueForMissingStub: _Fake$CategoriesTable_12(
              this,
              Invocation.getter(#categories),
            ),
          )
          as _i4.$CategoriesTable);

  @override
  _i4.$RolesTable get roles =>
      (super.noSuchMethod(
            Invocation.getter(#roles),
            returnValue: _Fake$RolesTable_13(this, Invocation.getter(#roles)),
            returnValueForMissingStub: _Fake$RolesTable_13(
              this,
              Invocation.getter(#roles),
            ),
          )
          as _i4.$RolesTable);

  @override
  _i4.$UsersTable get users =>
      (super.noSuchMethod(
            Invocation.getter(#users),
            returnValue: _Fake$UsersTable_14(this, Invocation.getter(#users)),
            returnValueForMissingStub: _Fake$UsersTable_14(
              this,
              Invocation.getter(#users),
            ),
          )
          as _i4.$UsersTable);

  @override
  _i4.$ItemsTable get items =>
      (super.noSuchMethod(
            Invocation.getter(#items),
            returnValue: _Fake$ItemsTable_15(this, Invocation.getter(#items)),
            returnValueForMissingStub: _Fake$ItemsTable_15(
              this,
              Invocation.getter(#items),
            ),
          )
          as _i4.$ItemsTable);

  @override
  _i4.$IngredientsTable get ingredients =>
      (super.noSuchMethod(
            Invocation.getter(#ingredients),
            returnValue: _Fake$IngredientsTable_16(
              this,
              Invocation.getter(#ingredients),
            ),
            returnValueForMissingStub: _Fake$IngredientsTable_16(
              this,
              Invocation.getter(#ingredients),
            ),
          )
          as _i4.$IngredientsTable);

  @override
  _i4.$RecipeIngredientsTable get recipeIngredients =>
      (super.noSuchMethod(
            Invocation.getter(#recipeIngredients),
            returnValue: _Fake$RecipeIngredientsTable_17(
              this,
              Invocation.getter(#recipeIngredients),
            ),
            returnValueForMissingStub: _Fake$RecipeIngredientsTable_17(
              this,
              Invocation.getter(#recipeIngredients),
            ),
          )
          as _i4.$RecipeIngredientsTable);

  @override
  _i4.$BranchIngredientStockTable get branchIngredientStock =>
      (super.noSuchMethod(
            Invocation.getter(#branchIngredientStock),
            returnValue: _Fake$BranchIngredientStockTable_18(
              this,
              Invocation.getter(#branchIngredientStock),
            ),
            returnValueForMissingStub: _Fake$BranchIngredientStockTable_18(
              this,
              Invocation.getter(#branchIngredientStock),
            ),
          )
          as _i4.$BranchIngredientStockTable);

  @override
  _i4.$StockReplenishmentRequestsTable get stockReplenishmentRequests =>
      (super.noSuchMethod(
            Invocation.getter(#stockReplenishmentRequests),
            returnValue: _Fake$StockReplenishmentRequestsTable_19(
              this,
              Invocation.getter(#stockReplenishmentRequests),
            ),
            returnValueForMissingStub: _Fake$StockReplenishmentRequestsTable_19(
              this,
              Invocation.getter(#stockReplenishmentRequests),
            ),
          )
          as _i4.$StockReplenishmentRequestsTable);

  @override
  _i4.$StockChangeRequestsTable get stockChangeRequests =>
      (super.noSuchMethod(
            Invocation.getter(#stockChangeRequests),
            returnValue: _Fake$StockChangeRequestsTable_20(
              this,
              Invocation.getter(#stockChangeRequests),
            ),
            returnValueForMissingStub: _Fake$StockChangeRequestsTable_20(
              this,
              Invocation.getter(#stockChangeRequests),
            ),
          )
          as _i4.$StockChangeRequestsTable);

  @override
  _i4.$DailySalesSummaryTable get dailySalesSummary =>
      (super.noSuchMethod(
            Invocation.getter(#dailySalesSummary),
            returnValue: _Fake$DailySalesSummaryTable_21(
              this,
              Invocation.getter(#dailySalesSummary),
            ),
            returnValueForMissingStub: _Fake$DailySalesSummaryTable_21(
              this,
              Invocation.getter(#dailySalesSummary),
            ),
          )
          as _i4.$DailySalesSummaryTable);

  @override
  _i5.OrganizationsDao get organizationsDao =>
      (super.noSuchMethod(
            Invocation.getter(#organizationsDao),
            returnValue: _FakeOrganizationsDao_22(
              this,
              Invocation.getter(#organizationsDao),
            ),
            returnValueForMissingStub: _FakeOrganizationsDao_22(
              this,
              Invocation.getter(#organizationsDao),
            ),
          )
          as _i5.OrganizationsDao);

  @override
  _i6.CategoriesDao get categoriesDao =>
      (super.noSuchMethod(
            Invocation.getter(#categoriesDao),
            returnValue: _FakeCategoriesDao_23(
              this,
              Invocation.getter(#categoriesDao),
            ),
            returnValueForMissingStub: _FakeCategoriesDao_23(
              this,
              Invocation.getter(#categoriesDao),
            ),
          )
          as _i6.CategoriesDao);

  @override
  _i7.RolesDao get rolesDao =>
      (super.noSuchMethod(
            Invocation.getter(#rolesDao),
            returnValue: _FakeRolesDao_24(this, Invocation.getter(#rolesDao)),
            returnValueForMissingStub: _FakeRolesDao_24(
              this,
              Invocation.getter(#rolesDao),
            ),
          )
          as _i7.RolesDao);

  @override
  _i8.UsersDao get usersDao =>
      (super.noSuchMethod(
            Invocation.getter(#usersDao),
            returnValue: _FakeUsersDao_25(this, Invocation.getter(#usersDao)),
            returnValueForMissingStub: _FakeUsersDao_25(
              this,
              Invocation.getter(#usersDao),
            ),
          )
          as _i8.UsersDao);

  @override
  _i9.ItemsDao get itemsDao =>
      (super.noSuchMethod(
            Invocation.getter(#itemsDao),
            returnValue: _FakeItemsDao_26(this, Invocation.getter(#itemsDao)),
            returnValueForMissingStub: _FakeItemsDao_26(
              this,
              Invocation.getter(#itemsDao),
            ),
          )
          as _i9.ItemsDao);

  @override
  _i10.IngredientsDao get ingredientsDao =>
      (super.noSuchMethod(
            Invocation.getter(#ingredientsDao),
            returnValue: _FakeIngredientsDao_27(
              this,
              Invocation.getter(#ingredientsDao),
            ),
            returnValueForMissingStub: _FakeIngredientsDao_27(
              this,
              Invocation.getter(#ingredientsDao),
            ),
          )
          as _i10.IngredientsDao);

  @override
  _i11.RecipeIngredientsDao get recipeIngredientsDao =>
      (super.noSuchMethod(
            Invocation.getter(#recipeIngredientsDao),
            returnValue: _FakeRecipeIngredientsDao_28(
              this,
              Invocation.getter(#recipeIngredientsDao),
            ),
            returnValueForMissingStub: _FakeRecipeIngredientsDao_28(
              this,
              Invocation.getter(#recipeIngredientsDao),
            ),
          )
          as _i11.RecipeIngredientsDao);

  @override
  _i12.BranchIngredientStockDao get branchIngredientStockDao =>
      (super.noSuchMethod(
            Invocation.getter(#branchIngredientStockDao),
            returnValue: _FakeBranchIngredientStockDao_29(
              this,
              Invocation.getter(#branchIngredientStockDao),
            ),
            returnValueForMissingStub: _FakeBranchIngredientStockDao_29(
              this,
              Invocation.getter(#branchIngredientStockDao),
            ),
          )
          as _i12.BranchIngredientStockDao);

  @override
  _i13.StockReplenishmentRequestsDao get stockReplenishmentRequestsDao =>
      (super.noSuchMethod(
            Invocation.getter(#stockReplenishmentRequestsDao),
            returnValue: _FakeStockReplenishmentRequestsDao_30(
              this,
              Invocation.getter(#stockReplenishmentRequestsDao),
            ),
            returnValueForMissingStub: _FakeStockReplenishmentRequestsDao_30(
              this,
              Invocation.getter(#stockReplenishmentRequestsDao),
            ),
          )
          as _i13.StockReplenishmentRequestsDao);

  @override
  _i14.StockChangeRequestsDao get stockChangeRequestsDao =>
      (super.noSuchMethod(
            Invocation.getter(#stockChangeRequestsDao),
            returnValue: _FakeStockChangeRequestsDao_31(
              this,
              Invocation.getter(#stockChangeRequestsDao),
            ),
            returnValueForMissingStub: _FakeStockChangeRequestsDao_31(
              this,
              Invocation.getter(#stockChangeRequestsDao),
            ),
          )
          as _i14.StockChangeRequestsDao);

  @override
  _i15.DailySalesSummaryDao get dailySalesSummaryDao =>
      (super.noSuchMethod(
            Invocation.getter(#dailySalesSummaryDao),
            returnValue: _FakeDailySalesSummaryDao_32(
              this,
              Invocation.getter(#dailySalesSummaryDao),
            ),
            returnValueForMissingStub: _FakeDailySalesSummaryDao_32(
              this,
              Invocation.getter(#dailySalesSummaryDao),
            ),
          )
          as _i15.DailySalesSummaryDao);

  @override
  Iterable<_i3.TableInfo<_i3.Table, Object?>> get allTables =>
      (super.noSuchMethod(
            Invocation.getter(#allTables),
            returnValue: <_i3.TableInfo<_i3.Table, Object?>>[],
            returnValueForMissingStub: <_i3.TableInfo<_i3.Table, Object?>>[],
          )
          as Iterable<_i3.TableInfo<_i3.Table, Object?>>);

  @override
  List<_i3.DatabaseSchemaEntity> get allSchemaEntities =>
      (super.noSuchMethod(
            Invocation.getter(#allSchemaEntities),
            returnValue: <_i3.DatabaseSchemaEntity>[],
            returnValueForMissingStub: <_i3.DatabaseSchemaEntity>[],
          )
          as List<_i3.DatabaseSchemaEntity>);

  @override
  _i3.StreamQueryUpdateRules get streamUpdateRules =>
      (super.noSuchMethod(
            Invocation.getter(#streamUpdateRules),
            returnValue: _FakeStreamQueryUpdateRules_33(
              this,
              Invocation.getter(#streamUpdateRules),
            ),
            returnValueForMissingStub: _FakeStreamQueryUpdateRules_33(
              this,
              Invocation.getter(#streamUpdateRules),
            ),
          )
          as _i3.StreamQueryUpdateRules);

  @override
  _i3.GeneratedDatabase get attachedDatabase =>
      (super.noSuchMethod(
            Invocation.getter(#attachedDatabase),
            returnValue: _FakeGeneratedDatabase_34(
              this,
              Invocation.getter(#attachedDatabase),
            ),
            returnValueForMissingStub: _FakeGeneratedDatabase_34(
              this,
              Invocation.getter(#attachedDatabase),
            ),
          )
          as _i3.GeneratedDatabase);

  @override
  _i3.DriftDatabaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeDriftDatabaseOptions_35(
              this,
              Invocation.getter(#options),
            ),
            returnValueForMissingStub: _FakeDriftDatabaseOptions_35(
              this,
              Invocation.getter(#options),
            ),
          )
          as _i3.DriftDatabaseOptions);

  @override
  _i3.DatabaseConnection get connection =>
      (super.noSuchMethod(
            Invocation.getter(#connection),
            returnValue: _FakeDatabaseConnection_36(
              this,
              Invocation.getter(#connection),
            ),
            returnValueForMissingStub: _FakeDatabaseConnection_36(
              this,
              Invocation.getter(#connection),
            ),
          )
          as _i3.DatabaseConnection);

  @override
  _i3.SqlTypes get typeMapping =>
      (super.noSuchMethod(
            Invocation.getter(#typeMapping),
            returnValue: _i18.dummyValue<_i3.SqlTypes>(
              this,
              Invocation.getter(#typeMapping),
            ),
            returnValueForMissingStub: _i18.dummyValue<_i3.SqlTypes>(
              this,
              Invocation.getter(#typeMapping),
            ),
          )
          as _i3.SqlTypes);

  @override
  _i3.QueryExecutor get executor =>
      (super.noSuchMethod(
            Invocation.getter(#executor),
            returnValue: _FakeQueryExecutor_37(
              this,
              Invocation.getter(#executor),
            ),
            returnValueForMissingStub: _FakeQueryExecutor_37(
              this,
              Invocation.getter(#executor),
            ),
          )
          as _i3.QueryExecutor);

  @override
  _i16.StreamQueryStore get streamQueries =>
      (super.noSuchMethod(
            Invocation.getter(#streamQueries),
            returnValue: _FakeStreamQueryStore_38(
              this,
              Invocation.getter(#streamQueries),
            ),
            returnValueForMissingStub: _FakeStreamQueryStore_38(
              this,
              Invocation.getter(#streamQueries),
            ),
          )
          as _i16.StreamQueryStore);

  @override
  _i3.DatabaseConnectionUser get resolvedEngine =>
      (super.noSuchMethod(
            Invocation.getter(#resolvedEngine),
            returnValue: _FakeDatabaseConnectionUser_39(
              this,
              Invocation.getter(#resolvedEngine),
            ),
            returnValueForMissingStub: _FakeDatabaseConnectionUser_39(
              this,
              Invocation.getter(#resolvedEngine),
            ),
          )
          as _i3.DatabaseConnectionUser);

  @override
  _i17.Future<T> executeInTransaction<T>(_i17.Future<T> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#executeInTransaction, [action]),
            returnValue:
                _i18.ifNotNull(
                  _i18.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#executeInTransaction, [action]),
                  ),
                  (T v) => _i17.Future<T>.value(v),
                ) ??
                _FakeFuture_40<T>(
                  this,
                  Invocation.method(#executeInTransaction, [action]),
                ),
            returnValueForMissingStub:
                _i18.ifNotNull(
                  _i18.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#executeInTransaction, [action]),
                  ),
                  (T v) => _i17.Future<T>.value(v),
                ) ??
                _FakeFuture_40<T>(
                  this,
                  Invocation.method(#executeInTransaction, [action]),
                ),
          )
          as _i17.Future<T>);

  @override
  _i3.Migrator createMigrator() =>
      (super.noSuchMethod(
            Invocation.method(#createMigrator, []),
            returnValue: _FakeMigrator_41(
              this,
              Invocation.method(#createMigrator, []),
            ),
            returnValueForMissingStub: _FakeMigrator_41(
              this,
              Invocation.method(#createMigrator, []),
            ),
          )
          as _i3.Migrator);

  @override
  _i17.Future<void> beforeOpen(
    _i3.QueryExecutor? executor,
    _i3.OpeningDetails? details,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#beforeOpen, [executor, details]),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Stream<T> createStream<T extends Object>(
    _i16.QueryStreamFetcher<T>? stmt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createStream, [stmt]),
            returnValue: _i17.Stream<T>.empty(),
            returnValueForMissingStub: _i17.Stream<T>.empty(),
          )
          as _i17.Stream<T>);

  @override
  T alias<T, D>(_i3.ResultSetImplementation<T, D>? table, String? alias) =>
      (super.noSuchMethod(
            Invocation.method(#alias, [table, alias]),
            returnValue: _i18.dummyValue<T>(
              this,
              Invocation.method(#alias, [table, alias]),
            ),
            returnValueForMissingStub: _i18.dummyValue<T>(
              this,
              Invocation.method(#alias, [table, alias]),
            ),
          )
          as T);

  @override
  void markTablesUpdated(Iterable<_i3.TableInfo<_i3.Table, dynamic>>? tables) =>
      super.noSuchMethod(
        Invocation.method(#markTablesUpdated, [tables]),
        returnValueForMissingStub: null,
      );

  @override
  void notifyUpdates(Set<_i3.TableUpdate>? updates) => super.noSuchMethod(
    Invocation.method(#notifyUpdates, [updates]),
    returnValueForMissingStub: null,
  );

  @override
  _i17.Stream<Set<_i3.TableUpdate>> tableUpdates([
    _i3.TableUpdateQuery? query = const _i3.TableUpdateQuery.any(),
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#tableUpdates, [query]),
            returnValue: _i17.Stream<Set<_i3.TableUpdate>>.empty(),
            returnValueForMissingStub:
                _i17.Stream<Set<_i3.TableUpdate>>.empty(),
          )
          as _i17.Stream<Set<_i3.TableUpdate>>);

  @override
  _i17.Future<T> doWhenOpened<T>(
    _i17.FutureOr<T> Function(_i3.QueryExecutor)? fn,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#doWhenOpened, [fn]),
            returnValue:
                _i18.ifNotNull(
                  _i18.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#doWhenOpened, [fn]),
                  ),
                  (T v) => _i17.Future<T>.value(v),
                ) ??
                _FakeFuture_40<T>(this, Invocation.method(#doWhenOpened, [fn])),
            returnValueForMissingStub:
                _i18.ifNotNull(
                  _i18.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#doWhenOpened, [fn]),
                  ),
                  (T v) => _i17.Future<T>.value(v),
                ) ??
                _FakeFuture_40<T>(this, Invocation.method(#doWhenOpened, [fn])),
          )
          as _i17.Future<T>);

  @override
  _i3.InsertStatement<T, D> into<T extends _i3.Table, D>(
    _i3.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#into, [table]),
            returnValue: _FakeInsertStatement_42<T, D>(
              this,
              Invocation.method(#into, [table]),
            ),
            returnValueForMissingStub: _FakeInsertStatement_42<T, D>(
              this,
              Invocation.method(#into, [table]),
            ),
          )
          as _i3.InsertStatement<T, D>);

  @override
  _i3.UpdateStatement<Tbl, R> update<Tbl extends _i3.Table, R>(
    _i3.TableInfo<Tbl, R>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [table]),
            returnValue: _FakeUpdateStatement_43<Tbl, R>(
              this,
              Invocation.method(#update, [table]),
            ),
            returnValueForMissingStub: _FakeUpdateStatement_43<Tbl, R>(
              this,
              Invocation.method(#update, [table]),
            ),
          )
          as _i3.UpdateStatement<Tbl, R>);

  @override
  _i3.SimpleSelectStatement<T, R> select<T extends _i3.HasResultSet, R>(
    _i3.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#select, [table], {#distinct: distinct}),
            returnValue: _FakeSimpleSelectStatement_44<T, R>(
              this,
              Invocation.method(#select, [table], {#distinct: distinct}),
            ),
            returnValueForMissingStub: _FakeSimpleSelectStatement_44<T, R>(
              this,
              Invocation.method(#select, [table], {#distinct: distinct}),
            ),
          )
          as _i3.SimpleSelectStatement<T, R>);

  @override
  _i3.JoinedSelectStatement<T, R> selectOnly<T extends _i3.HasResultSet, R>(
    _i3.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            returnValue: _FakeJoinedSelectStatement_45<T, R>(
              this,
              Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            ),
            returnValueForMissingStub: _FakeJoinedSelectStatement_45<T, R>(
              this,
              Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            ),
          )
          as _i3.JoinedSelectStatement<T, R>);

  @override
  _i3.BaseSelectStatement<_i3.TypedResult> selectExpressions(
    Iterable<_i3.Expression<Object>>? columns,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#selectExpressions, [columns]),
            returnValue: _FakeBaseSelectStatement_46<_i3.TypedResult>(
              this,
              Invocation.method(#selectExpressions, [columns]),
            ),
            returnValueForMissingStub:
                _FakeBaseSelectStatement_46<_i3.TypedResult>(
                  this,
                  Invocation.method(#selectExpressions, [columns]),
                ),
          )
          as _i3.BaseSelectStatement<_i3.TypedResult>);

  @override
  _i3.DeleteStatement<T, D> delete<T extends _i3.Table, D>(
    _i3.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [table]),
            returnValue: _FakeDeleteStatement_47<T, D>(
              this,
              Invocation.method(#delete, [table]),
            ),
            returnValueForMissingStub: _FakeDeleteStatement_47<T, D>(
              this,
              Invocation.method(#delete, [table]),
            ),
          )
          as _i3.DeleteStatement<T, D>);

  @override
  _i17.Future<int> customUpdate(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i3.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customUpdate,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i17.Future<int>.value(0),
            returnValueForMissingStub: _i17.Future<int>.value(0),
          )
          as _i17.Future<int>);

  @override
  _i17.Future<int> customInsert(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customInsert,
              [query],
              {#variables: variables, #updates: updates},
            ),
            returnValue: _i17.Future<int>.value(0),
            returnValueForMissingStub: _i17.Future<int>.value(0),
          )
          as _i17.Future<int>);

  @override
  _i17.Future<List<_i3.QueryRow>> customWriteReturning(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i3.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customWriteReturning,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i17.Future<List<_i3.QueryRow>>.value(
              <_i3.QueryRow>[],
            ),
            returnValueForMissingStub: _i17.Future<List<_i3.QueryRow>>.value(
              <_i3.QueryRow>[],
            ),
          )
          as _i17.Future<List<_i3.QueryRow>>);

  @override
  _i3.Selectable<_i3.QueryRow> customSelect(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelect,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_48<_i3.QueryRow>(
              this,
              Invocation.method(
                #customSelect,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
            returnValueForMissingStub: _FakeSelectable_48<_i3.QueryRow>(
              this,
              Invocation.method(
                #customSelect,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i3.Selectable<_i3.QueryRow>);

  @override
  _i3.Selectable<_i3.QueryRow> customSelectQuery(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelectQuery,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_48<_i3.QueryRow>(
              this,
              Invocation.method(
                #customSelectQuery,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
            returnValueForMissingStub: _FakeSelectable_48<_i3.QueryRow>(
              this,
              Invocation.method(
                #customSelectQuery,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i3.Selectable<_i3.QueryRow>);

  @override
  _i17.Future<void> customStatement(String? statement, [List<dynamic>? args]) =>
      (super.noSuchMethod(
            Invocation.method(#customStatement, [statement, args]),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<T> transaction<T>(
    _i17.Future<T> Function()? action, {
    bool? requireNew = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #transaction,
              [action],
              {#requireNew: requireNew},
            ),
            returnValue:
                _i18.ifNotNull(
                  _i18.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #transaction,
                      [action],
                      {#requireNew: requireNew},
                    ),
                  ),
                  (T v) => _i17.Future<T>.value(v),
                ) ??
                _FakeFuture_40<T>(
                  this,
                  Invocation.method(
                    #transaction,
                    [action],
                    {#requireNew: requireNew},
                  ),
                ),
            returnValueForMissingStub:
                _i18.ifNotNull(
                  _i18.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #transaction,
                      [action],
                      {#requireNew: requireNew},
                    ),
                  ),
                  (T v) => _i17.Future<T>.value(v),
                ) ??
                _FakeFuture_40<T>(
                  this,
                  Invocation.method(
                    #transaction,
                    [action],
                    {#requireNew: requireNew},
                  ),
                ),
          )
          as _i17.Future<T>);

  @override
  _i17.Future<T> exclusively<T>(_i17.Future<T> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#exclusively, [action]),
            returnValue:
                _i18.ifNotNull(
                  _i18.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#exclusively, [action]),
                  ),
                  (T v) => _i17.Future<T>.value(v),
                ) ??
                _FakeFuture_40<T>(
                  this,
                  Invocation.method(#exclusively, [action]),
                ),
            returnValueForMissingStub:
                _i18.ifNotNull(
                  _i18.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#exclusively, [action]),
                  ),
                  (T v) => _i17.Future<T>.value(v),
                ) ??
                _FakeFuture_40<T>(
                  this,
                  Invocation.method(#exclusively, [action]),
                ),
          )
          as _i17.Future<T>);

  @override
  _i17.Future<void> batch(
    _i17.FutureOr<void> Function(_i3.Batch)? runInBatch,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#batch, [runInBatch]),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<T> runWithInterceptor<T>(
    _i17.Future<T> Function()? action, {
    required _i3.QueryInterceptor? interceptor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #runWithInterceptor,
              [action],
              {#interceptor: interceptor},
            ),
            returnValue:
                _i18.ifNotNull(
                  _i18.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #runWithInterceptor,
                      [action],
                      {#interceptor: interceptor},
                    ),
                  ),
                  (T v) => _i17.Future<T>.value(v),
                ) ??
                _FakeFuture_40<T>(
                  this,
                  Invocation.method(
                    #runWithInterceptor,
                    [action],
                    {#interceptor: interceptor},
                  ),
                ),
            returnValueForMissingStub:
                _i18.ifNotNull(
                  _i18.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #runWithInterceptor,
                      [action],
                      {#interceptor: interceptor},
                    ),
                  ),
                  (T v) => _i17.Future<T>.value(v),
                ) ??
                _FakeFuture_40<T>(
                  this,
                  Invocation.method(
                    #runWithInterceptor,
                    [action],
                    {#interceptor: interceptor},
                  ),
                ),
          )
          as _i17.Future<T>);

  @override
  _i3.GenerationContext $write(
    _i3.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$write,
              [component],
              {#hasMultipleTables: hasMultipleTables, #startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_49(
              this,
              Invocation.method(
                #$write,
                [component],
                {
                  #hasMultipleTables: hasMultipleTables,
                  #startIndex: startIndex,
                },
              ),
            ),
            returnValueForMissingStub: _FakeGenerationContext_49(
              this,
              Invocation.method(
                #$write,
                [component],
                {
                  #hasMultipleTables: hasMultipleTables,
                  #startIndex: startIndex,
                },
              ),
            ),
          )
          as _i3.GenerationContext);

  @override
  _i3.GenerationContext $writeInsertable(
    _i3.TableInfo<_i3.Table, dynamic>? table,
    _i3.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$writeInsertable,
              [table, insertable],
              {#startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_49(
              this,
              Invocation.method(
                #$writeInsertable,
                [table, insertable],
                {#startIndex: startIndex},
              ),
            ),
            returnValueForMissingStub: _FakeGenerationContext_49(
              this,
              Invocation.method(
                #$writeInsertable,
                [table, insertable],
                {#startIndex: startIndex},
              ),
            ),
          )
          as _i3.GenerationContext);

  @override
  String $expandVar(int? start, int? amount) =>
      (super.noSuchMethod(
            Invocation.method(#$expandVar, [start, amount]),
            returnValue: _i18.dummyValue<String>(
              this,
              Invocation.method(#$expandVar, [start, amount]),
            ),
            returnValueForMissingStub: _i18.dummyValue<String>(
              this,
              Invocation.method(#$expandVar, [start, amount]),
            ),
          )
          as String);
}
